### ISSUE TITLE
XML Sitemap - Add a feature for importing URLs into our XML sitemap

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#103]
In our XML Sitemap module we have a feature where you can add additional URLs to be included in the XML sitemap (http://semperplugins.com/documentation/xml-sitemaps-module/#additional-pages).

Users who want to add URLs in bulk would like a feature to import URLs to be included here.  

We need a feature added where a user can import URLs with optional fields for Priority, Frequency and Last Modified via a CSV file.  There should be an Import URLs button which would launch the file upload modal where you can select the CSV file and upload it.  Imported URLs would appear in this Additional Pages section.  Only URLs for the domain of the site should be allowed, external URLs should be rejected.

**Comment by wpsmort** [comment]
Requested today here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/bulk-add-additional-pages-to-sitemap-xml/

**Comment by michaeltorbert** [comment]
Importing would be bad, because we have to put the URLs somewhere. They'd need to go in an external table, custom post type, or field in the options table. All three of these are bad.

However, a user could have a CSV (or whatever type we decide) file in whatever format we decide, and we read them then hook into our sitemap additional pages hook. This could also be an add-on plugin (free or paid) or in Pro.

**Comment by michaeltorbert** [comment]
We already have a filter hook for this, which I believe is used by the SimplePress AIOSEOP xml sitemap add-on.
