### ISSUE TITLE
Change behavior of help text area

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1156]
Instead of moving everything down and inserting the text (which uses a lot of code and has caused bugs in the past) maybe there's another way. 
Popup tooltip? How can we make this look better?

**Comment by michaeltorbert** [comment]
@EkoJr discussed wanting to do this with jQuery UI Dialogs.

**Comment by EkoJr** [comment]
As discussed: Implementing jQuery UI Tooltips instead.

**Comment by EkoJr** [comment]
Both Tooltips and Dialogs were added for testing. Tooltips seem to work quite well, but dialogs seem problematic anyways. Here are some of the notes I added of the changes that were made.

* **Dialogs** were added on the Top Right of the metabox, inside the metabox title container (Next to the Help link).
  * Dialog content is added/included from a separate file that is unique to the metabox.
  * ISSUE: Clicking the Info/Help link multiple times causes multiple dialog boxes to appear.
  * ISSUE: Top bar will occasionally appear out of view if there is a large amount of content in a given width.
* **Tooltips** were added to the option labels on the left side. It appears on hover, rather than click.
  * Adding it to the input element area seemed possible, but obscuring the option was a worry.
  * Possibly able to customize the tooltip to show/hide on click rather on hover.
  * Could add a delay on hide.
  * Option Help Text will need to be changed to remove raw HTML that was used for links (image has page edits showing the intended version).
* jQuery UI Styles were (temporarily) added in order to render properly. It was mainly intended for testing. Unsure on this as a final method, but added as a note.
  * `\all-in-one-seo-pack\admin\aioseop_module_class.php` at `All_in_One_SEO_Pack_Module::enqueue_styles()`
  * It uses a Google CDN that is updated according to what version WP has for the scripts.
  * Uses the same method I applied here [StackOverflow: WordPress, jQuery UI CSS Files?](https://stackoverflow.com/questions/8849684/wordpress-jquery-ui-css-files/11789443#11789443)
* Dependants were added to wp_enqueue_script() for aioseop_module.js
  * In the past I’ve used dependants with WP when enqueueing script, but I noticed AIOSEO is a bit different with jQuery (didn’t seem to use jQuery UI).
  * Added a variable to JS localization in order to identify and initialize the element ui.

**Comment by wpsmort** [comment]
Notes from Skype call with @EkoJr 

@EkoJr demoed the new tooltips and they look and work fine.  We discussed the popup dialogs and I told him not to spend any more time on those.  We will leave the main Help links as they are for now.

We discussed the following with regards to the tooltips replacing inline help for options:

- We do not need any delay on the tooltip, a standard tooltip which works on hover is what we want to do
- We need to make sure that we avoid any jQuery conflicts with other plugins/themes.  We'll only want to load our jQuery on the AIOSEOP options screens as well as the Edit Post screens.  It's the Edit Post screen where there's the highest likelihood of a conflict
- We would like to migrate all the current inline help text into a self contained file, it's currently all in the main class file.  @EkoJr will look to see if he can do this

**Comment by EkoJr** [comment]
I did find a resolve with the tooltips (with Caldera Forms). The solution was wrapping the code in an anonymous function.

I also made a method that will allow HTML to be added, but may be limited with rendering on jQuery (which, I also made a RegEx alternative). This is useful if you need newlines, but any links would still be excluded.

So, now I feel confident to adding it to AIOSEO, I'll proceed with the concept (will continue to keep an eye out for bugs). The conflicts were a big worry, and I wanted to test various ideas on a separate project that I handle in the case it might of been a flawed concept.

**Comment by arnaudbroes** [comment]
@EkoJr @michaeltorbert 
Let me know when this is finalized so I can do #1320.

**Comment by EkoJr** [comment]
@michaeltorbert @arnaudbroes 
I happen to catch a possible future bug in `All_in_One_SEO_Pack_Module::add_help_text_links()`. Looks like I'll need to both remove the old variable operation and add the new Helper Class to that area.

I suspect the plugin is running off of old data save on the database somehow, but haven't tested on a fresh install. Either way, it has to go.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1314/commits/1e97150849632e918f0b7f30da3dabdd7b1c8728#diff-604ad90165044b2b600ad4f4148dfacaR1692

**Comment by michaeltorbert** [comment]
I have two comments:

1) When hovering over a label, such as "Home Title" or "Use Static Front Page Instead," the curser changes as though it can be clicked on, but clicking the text of course no longer does anything. I'd think   it should either a) not turn into a hand or b) stay a hand point and when clicked on go to the documentation page.

2) Somewhat related to 1, the behavior of "Help" vs the other ones "Enable Custom Canonical URLs" (for example) is different, which could be confusing.

These issues can be discussed, and don't necissarly need tohelp up this issue, so I'll go ahead and merge the PR and open a new issue for these.

**Comment by wpsmort** [comment]
@michaeltorbert @EkoJR Here are my recommendations for making this more intuitive:

1. The cursor should change to a question mark when it's over the help icon.  This would match what WooCommerce does when you mouse over their help icons.

2. When you mouse over the label text the mouse should remain as the default cursor.  It should not change to a hand because the label text is not a link.

3. For the main Help link in the top right of each meta box, this should remain as it is.  The hand denotes this is a link.

**Comment by EkoJR** [comment]
1. I agree.
2. I think this was either pre-existing or a browser default. I can look into changing this as well.
3. I agree. Probably just needs a seperate css class.
