### ISSUE TITLE
Better check for images in galleries - alternative to the_content filter for image sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1191]
In #1187 I’ve removed the apply_filter for now, because it breaks in some cases where things are output to the screen on the filter.
So we’ll need to find some way around that long-term.

I figured not applying it and not getting images added by the_content was better than applying it and having it break some site.

**Comment by contactashish13** [comment]
@michaeltorbert can you please tell me how to replicate this?

> because it breaks in some cases where things are output to the screen on the filter.

**Comment by michaeltorbert** [comment]
@contactashish13 I recommend reading all of #1187, and you can follow my progress yesterday.
Steps to reproduce are here: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1187#issuecomment-332629386

**Comment by wpsmort** [comment]
We discussed this today and agreed to release v2.4 without the apply_filter.  We now know that it's needed in order to discover images in galleries added via the default WordPress Media Library gallery functionality.  It may also be needed to discover images added via other gallery plugins/shortcodes. 

We know that the_content filter causes a conflict with plugins such as WP Affiliate Platform where  they are echoing things such as stylesheets out to the post content.  We need a workaround that does not cause a conflict with plugins that do this.

**Comment by contactashish13** [comment]
@wpsmort have fixed this by removing the filter and fetching galleries using core WP functions. PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1204

**Comment by wpsmort** [comment]
@michaeltorbert PR #1204 has been tested and is good.  

Note: This only adds support for the built in WordPress gallery and does not work with other galleries that use shortcodes such as JetPack and NextGen Gallery.  I've opened Issue #1230 for this enhancement.
