### ISSUE TITLE
Filter for adding shortcodes with images for sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1207]
Since we can't apply the_content filter when looking for images for the sitemap, we should have a filter that plugin devs or site owners can use to have their shortcodes be seen by our image scanning for the sitemap.

**Comment by contactashish13** [comment]
@wpsmort @michaeltorbert  PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1214

**Comment by contactashish13** [comment]
@wpsmort you can use this

`
add_filter( 'aioseop_image_shortcodes', 'aioseop_image_shortcodes', 10, 1 );
function aioseop_image_shortcodes( $shortcodes ) {
$shortcodes = '[xxx] [yyy] zzzz [aaaa]';
return $shortcodes;
}
`

**Comment by contactashish13** [comment]
@wpsmort moving the discussion from the PR here so that all relevant information is in one place.

The snippet here https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1207#issuecomment-374914932 will add to every post. The signature of the filter needs to be changed below and then filtered according to the post. Let me know if this does not work.

`
add_filter( 'aioseop_image_shortcodes', 'aioseop_image_shortcodes', 10, 2 );

function aioseop_image_shortcodes( $shortcodes, $post ) {
...
}
`

**Comment by wpsmort** [comment]
Requested again here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/images-not-being-indexed/

**Comment by michaeltorbert** [comment]
Redundant pr 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1230
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1546
