### ISSUE TITLE
Sitemap not working properly

### ISSUE THREAD

**Issue by hsbahri** [semperfiwebdesign/all-in-one-seo-pack#1220]
I have All in One SEO plugin installed since, more than a year. Suddenly, I noticed Google giving me an error that sitemap issue is there. Then, I found my sitemap page was showing blank. Then, I made a settings change to this and clicked on enable sitemap index. Then, though my sitemap started working (https://www.thebuzzstand.com/sitemap.xml), but then a sub sitemap https://www.thebuzzstand.com/sitemap_attachment.xml now shows a blank page. Even though when you right click on it you are able to view the code to be present. How can I fix this?

**Comment by wpsmort** [comment]
@hsbahri This is most likely caused because PHP is running out of memory when trying to build that sitemap due to the large number of URLs on it.  You may need to increase the memory allocated to PHP (https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP) or decrease the number of posts per page in the XML Sitemap settings (https://semperplugins.com/documentation/xml-sitemaps-module/#enable-sitemap-indexes).  Also, if you don't use Image Attachment Pages in WordPress, which most people do not, then you can uncheck the Media / Attachments checkbox in the XML Sitemap settings and that will resolve this problem.
