### ISSUE TITLE
Google Search Console validation error in 2.4.1.1

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1250]
Reported by Bimal via email and 

https://wordpress.org/support/topic/google-webmaster-sitemap-error/

**Comment by michaeltorbert** [comment]
Looking at the site, this is the first image:

https://i2.wp.com/moviesweed.com/wp-content/uploads/2017/10/Tiger-Zinda-Hai-2017-Hindi-Movie-Poster.jpg?resize=150%2C150&ssl=1

Do we just need to strip all the extra url vars?

**Comment by michaeltorbert** [comment]
I'm creating a backup and clone of his site for testing.

**Comment by contactashish13** [comment]
@michaeltorbert this type of URL will automatically be excluded with the changes in #1212

**Comment by michaeltorbert** [comment]
@contactashish13 It isn't though, he's running 2.4.1.1 which has PR #1215 in it.

**Comment by bimal008** [comment]
@contactashish13 , @michaeltorbert hi,
do you have an idea yet, why its causing error in google webmaster sitemap section ?

**Comment by bimal008** [comment]
Re-submit http://prntscr.com/gsrcay  > same error yet http://prntscr.com/gsrcpn

**Comment by michaeltorbert** [comment]
@bimal008 As you can see, we're working on it now. There's no need for repeated messages.

**Comment by wpsmort** [comment]
@michaeltorbert I was able to reproduce the error on my site.  When submitting the XML Sitemap to GWT I was able to get the same parsing error.  It was caused by the &ssl=1 part of the image URL. 

Once I could reproduce the problem, I tested PR #1253 and I confirmed that this fixed the problem.  In addition to fixing the parsing error in GWT, I also found that this fixes the blank sitemap problem reported by Bimal.  Again, this was caused by the &ssl=1 part of the image URL.  Removing that fixed the blank sitemap. 

I verified this on a brand new site and as soon as I added a second URL parameter separated by an & then both errors occurred.

PR #1253 is ready for code review.

**Comment by contactashish13** [comment]
@wpsmort I reached the same conclusion at around the same time after a long struggle :) @michaeltorbert I have created a new PR with a sub-branch of #1253 because I'm making the image URL xml-safe in the same function I had added earlier. PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1256

**Comment by wpsmort** [comment]
See PR #1256

**Comment by bimal008** [comment]
See PR #1256
<https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1256>  >
michaeltorbert removed their assignment an hour ago
http://prntscr.com/gsweda .

**Comment by michaeltorbert** [comment]
@bimal008 ?

**Comment by bimal008** [comment]
Hi Michael

Is this issue resolved yet ? (
https://wordpress.org/support/topic/google-webmaster-sitemap-error/)

**Comment by michaeltorbert** [comment]
@bimal008 This issue will be fixed in the next release. Constant messages are not necessary and only distract us from development.
