### ISSUE TITLE
Remove from sitemap when noindex is enabled

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1382]
Reported by Gordon via email. 

We should consider whether to remove a post from the XML sitemap with the noindex option is enabled. This makes sense, although it may make "exclude from sitemap" redundant. 
If we do this, we should consider whether to remove the latter option.

It was suggested that excluding a post from XML might prevent Google and other crawlers from reading the noindex and therefore continuing to list the sites.

**Comment by arnaudbroes** [comment]
@michaeltorbert good thinking, I'd remove the "exclude from sitemap" setting. Using NOINDEX makes more sense.

**Comment by contactashish13** [comment]
@michaeltorbert would this also need to be backward compatible for users who had excluded pages from sitemap and now find the option gone?

**Comment by michaeltorbert** [comment]
Requested again by Serhat via email


Hello,You need to bring the "exclude from sitemap" option for the Woocommerce categories. I set "No-Index" for a category and now Google Search Console warns me to drop that category URL from the sitemap.See the screenshot: https://www.dropbox.com/s/wlt66xa5f0530ls/screenshot.47.png?dl=0
--

**Comment by arnaudbroes** [comment]
I think we should just remove the Exclude from Sitemap setting altogether then and merge it with noindex.

**Comment by wpsmort** [comment]
Requested again - https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/since-more-than-week-google-doesnt-index-posts/

**Comment by yatgirl** [comment]
and also product tag archive pages - I have 14 product tag archive pages that I am receiving google errors on because I have set them to no index, but they are still being included in the sitemap. I am hoping this can be resolved so I can clear the errors in google webmaster very shortly.
[https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/tag-archive-sitemap/](url)

**Comment by contactashish13** [comment]
what's the consensus on this approach?

**Comment by michaeltorbert** [comment]
Reason **_to_** merge-

1)We have basically three places people can tell search engines not to look at a page: Sitemap options page (excluded pages), exclude this page option on the edit page itself, noindex on the edit page itself. This can be confusing.


Reason **_not to_** merge

1) backwards compatibility - as mentioned by Ashish. It would take quite a db migration to move all that over. Otherwise, we have to forever support the old settings (also a possibility).

**Comment by michaeltorbert** [comment]
Let's leave the options the way they are, but start excluding noindexed pages from the sitemap.
We can address the overlapping issues later.

**Comment by contactashish13** [comment]
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2264

@michaeltorbert do you think is required even for categories when using PRO?

**Comment by michaeltorbert** [comment]
> PR #2264
> 
> @michaeltorbert do you think is required even for categories when using PRO?

I've opened an issue so we can discuss it. https://github.com/semperfiwebdesign/aioseop-pro/issues/470

**Comment by EkoJR** [comment]
When a Post Type is selected to be NoIndexed, should we probably grey-out the option in the post since it is intended for the same purpose. Currently to the user it acts as a boolean to noindex; the backend does have on, off, and empty.

If someone wants a Post to be indexed on a noindex Post Type, then we'll have to add/change the option, either as another boolean setting, or a select-option/ratio.

**Comment by contactashish13** [comment]
What you are recommending is future behavior. My comment was pertinent to existing users who might have a variety of these settings. We need a combination of both to address this issue permanently.

**Comment by EkoJR** [comment]
I'm referring to the post editor. The `null` and "off" options acts as one in the same in the UI, and I also ran a file search and did not find anything that checked if it was off; I only saw checks for `'on'`, `''`, & `empty()`.

As for future implementation, the UI option could be better defined when adding 'Index posts on NoIndex post type' #2323.

However, for `noindex === 'on'` it is definitive setting. So that's what my PR focused on filtering out.
