### ISSUE TITLE
Look at file_get_contents in sitemap class

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1428]
See if this can be improved in some way.  

Some hosts can potentially have  a problem with seeking https://wordpress.org/support/topic/errors-creating-sitemap/#post-9808145

> The problem is on a line with file_get_contents, and seems to be with the offset parameter. https://secure.php.net/manual/en/function.file-get-contents.php “Seeking (offset) is not supported with remote files. Attempting to seek on non-local files may work with small offsets, but this is unpredictable because it works on the buffered stream.”

**Comment by michaeltorbert** [comment]
User reports error only comes on PHP 7.10

According to the changelog for PHP: "7.1.0 | Support for negative offsets has been added."
This should be investigated.

**Comment by EkoJr** [comment]
I've been able to reproduce the issue, and investigated it a bit, and it seems the main issue is the difference between remote and local. Both files are local, but the compression prefix is causing PHP to recognize the string file path to be a remote file. The .xml file however works fine.

The issue also seems to be the cause of another issue, and happens that the warning function used also throws a PHP Warning since 7.1.0+.

Callstack
```
#	Time	Memory	    Function	                                           Location
1	0.0000	459168          {main}( )                                              ...\admin.php:0
2	0.4280	32825256	do_action( )                                           ...\admin.php:224
3	0.4280	32825632	WP_Hook->do_action( )                                  ...\plugin.php:453
4	0.4280	32825632	WP_Hook->apply_filters( )                              ...\class-wp-hook.php:310
5	0.4280	32826648	All_in_One_SEO_Pack_Sitemap->display_settings_page( )  ...\class-wp-hook.php:286
6	3.9022	42739440	do_action( )                                           ...\aioseop_module_class.php:2591
7	3.9022	42739816	WP_Hook->do_action( )                                  ...\plugin.php:453
8	3.9022	42739816	WP_Hook->apply_filters( )                              ...\class-wp-hook.php:310
9	3.9022	42740808	All_in_One_SEO_Pack_Sitemap->do_sitemap_scan( )        ...\class-wp-hook.php:286
10	3.9022	42740808	All_in_One_SEO_Pack_Sitemap->scan_sitemaps( )          ...\aioseop_sitemap.php:965
11	3.9132	42741320	All_in_One_SEO_Pack_Sitemap->sitemap_warning( )        ...\aioseop_sitemap.php:982
12	3.9132	42741344	All_in_One_SEO_Pack_Sitemap->get_problem_files( )      ...\aioseop_sitemap.php:1083
13	3.9212	42759152	file_get_contents ( )                                  ...\aioseop_sitemap.php:1034
```

## Reproduce

This issue also affects other versions from 7.1.0 to 7.2.0 (current), and can be reproduced fairly easy. To reproduce...

* Go to XML Sitemap settings, and under the XML Sitemap metabox.
* Check "Create Compressed Sitemap".
* Un-check "Dynamically Generate Sitemap".
* Saving options by clicking "Update Sitemap" button will trigger the bug.

## Solution

I was thinking of handling the compress file separately with PHP's [gzfile()](http://php.net/manual/en/function.gzfile.php) for this section of code, but the initial problem seems to be handled differently using WP's filesystem object; which may need to be investigated further.

**Comment by EkoJr** [comment]
## Reproduce

Additional environmental conditions that may contribute to bug...

* Unknown Rewrite issue. Was possibly the main contributor to the PHP error message itself being triggered, but was not the root issue. In my case, it was the localhost URL that I suspected.

## 7.1.0+ PHP Development

It may already be assumed that this was an intended change with PHP, and when investigating the matter, it may lead someone to believe that this is a PHP bug; there are some mentions of 7.1+ issues related to the new forced rule. So this may or may not be a PHP bug.

The reason for the change was due to an exploit that could allow hackers to get into a server through a remote file being used. However, AIOSEOP files are locally stored, but the issue is with the [compress streams](http://php.net/manual/en/wrappers.compression.php) in [file_get_contents()](http://php.net/manual/en/function.file-get-contents.php). Which makes it appear as a bug, or a feature/concept that hasn't been added to Compression Streams yet; possibly being fixed/added in the future

As of AIOSEOP, the equivalent would be [gzopen()](http://php.net/manual/en/function.gzopen.php), [gzread()](http://php.net/manual/en/function.gzread.php), and [gzclose()](http://php.net/manual/en/function.gzclose.php), and would be more manually controlled, but does add some extra lines of code.

## Commit

Compress files are handled separately to prevent conflicts, and the offset for files_get_content() was changed from **-1** to **0** to fix what lead the sitemap not being recognized, and possibly deleted.

A note/todo was added which identifies a possible flaw; may be partially intended.

## Additional Resources

* WordPress
	* [errors creating sitemap](https://wordpress.org/support/topic/errors-creating-sitemap/) - Main issue.
	* [xml sitemap Fatal error: require_once(): Failed opening required](https://wordpress.org/support/topic/xml-sitemap-fatal-error-require_once-failed-opening-required/) - related issue that had multiple issues collected, and was resolved possibly by changing the conditions. *Rewrite issue possibly.*
* StackOverflow [Unzip or inflate php://input stream?](https://stackoverflow.com/questions/44981813/unzip-or-inflate-php-input-stream) ( Posted 07/08/2017 ) - Explains it further in great detail as to why, and other methods that could be used.

**Comment by wpsmort** [comment]
@EkoJr Is there a PR for this?

**Comment by michaeltorbert** [comment]
@wpsmort It looks like https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1435 is referencing this issue.
