### ISSUE TITLE
broken aioseop_description filter

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1468]
2.4.4 possibly broke the aioseop_description filter in some cases.
Reported here: https://wordpress.org/support/topic/apply_filters-aioseop_description/

We should try and reproduce this and determine under what conditions it would be the case.
I'd say at a minimum, it probably happens when there's a manually entered description.

Try and find anything moving the filter may have broken.

**Comment by michaeltorbert** [comment]
Reported again by Marco via email:

_i use this filter:

add_filter( 'aioseop_description', 'sfwd_description_comment_page_num' );
function sfwd_description_comment_page_num( $description ) {
$cpage = get_query_var( 'cpage' );
if ( !empty( $cpage ) ) $description = "Pag. n.$cpage - " . $description;
return $description;
}

Unfortunately, it doesn't work anymore after the latest update_

**Comment by EkoJr** [comment]
Place the the `apply_filter('aioseop_description')` back to where it was.

Then apply truncate with the global variable `$aioseop_options['aiosp_dont_truncate_descriptions']` since it seems to be based on it and doesn't appear to be set anywhere. **Still unsure if it is implemented elsewhere**

Inside `All_in_One_SEO_Pack::filter_description()` had to add a boolean check instead of just checking `! empty()`. Which appears to be a function bug where the string is trimmed even if the value is false.

```
if ( ! empty( $truncate ) && $truncate )
	$value = $this->trim_excerpt_without_filters( $value );
// Encode to valid SEO html entities
return $this->seo_entity_encode( $value );
```

**Comment by michaeltorbert** [comment]
Marco confirmed that for him, the problem occurs for a manually entered meta description (not being able to filter it).
We need to make sure the fix doesn't break anything else.

**Comment by michaeltorbert** [comment]
Possibly related to #1469

**Comment by wpsmort** [comment]
@EkoJr I missed one problem with the filter code in PR #1470. That filter doesn't work for taxonomies because it's using get_post_meta.  I believe you need to add get_term_meta for taxonomies.

Note that SEO for taxonomies is only for AIOSEOP Pro.  You can detect if you're in Pro by looking for the AIOSEOPPRO constant boolean.

**Comment by EkoJr** [comment]
@wpsmort Looks like the initial filter still works. This is the 3rd truncate code though, which seemed to give you trouble. Let me know where any issues continue.

```
add_filter( 'aioseop_description', 'manual_description_force_truncate_3', 9, 2 );
function manual_description_force_truncate_3( $description, $truncate = false ) {
	global $post;

	$aioseop_desc = '';
	if ( is_front_page() || is_single() || is_page() || is_attachment() || is_home() ) {
		if ( ! empty( $post->ID ) ) {
			$aioseop_desc = get_post_meta( $post->ID, '_aioseop_description', true );
		}

		if ( ! empty( $aioseop_desc ) ) {
			$description = substr( $description, 0, 320 );
		}
	} else if ( is_category() || is_tag() || is_tax() ) {
		if ( AIOSEOPPRO ) {
			$queried_object = get_queried_object();
			$term_meta = '';
			if ( ! empty( $queried_object ) && ! empty( $queried_object->term_id ) ) {
				$term_meta = get_term_meta( $queried_object->term_id, '_aioseop_description', true );
			}
			if ( ! empty( $term_meta ) ) {
				$description = substr( $description, 0, 320 );
			}
		}
	}

	return $description;
}
```

**Comment by wpsmort** [comment]
I have confirmed that the filter above works for taxonomies.  I have added documentation on this filter here - https://semperplugins.com/documentation/truncate-manually-entered-seo-descriptions/
