### ISSUE TITLE
XML Sitemap - Add support for post type archive pages and support to exclude them as well

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#155]
XML Sitemap - Add support for post type archive pages and support to exclude them as well

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1480

There could a tiny confusion on how this will work. 

Current behavior: **If the user checks no post types and checks date archives, the post archive pages are being included in the sitemap.**

Changed behavior: I'm automatically including the date archives of the supported post types (can be switched off with a filter). So if the user checks product and post and date archives, it will show the date archives for these post types. **If the user checks no post types and checks date archives, nothing will be included in the sitemap.**

This might cause confusion because users currently expect date archives to be included even if none of the post types are checked. To support this case, I'm assuming that if no post type is checked for date archives then I need to assume that at least the "post" post_type is to be included. @wpsmort Let me know if this is alright.

**Comment by wpsmort** [comment]
@contactashish13 I tested this and it did not work.  Here's how it should work:

If a post type has an archive (https://codex.wordpress.org/Function_Reference/register_post_type#has_archive) then we should include that archive in the XML Sitemap if that post type is checked.

To test this follow these steps:

1). Create a custom post type and make sure that has_archive is set to true
2). Populate the post type with a couple of posts and make sure you can browse to the archive page.  I created a CPT called Movies and was able to browse to mydomain.com/movies/ to view all my movies posts
3). Check the box for your CPT under XML Sitemap > Post Types to include your CPT content in the sitemap
4). Check the XML Sitemap, you should see your posts and the archive page.  You should not need Date Archives or any other option checked for this to happen

Note that excluding them will be difficult because they don't have a page ID.  We should discuss how to exclude them.

Let me know if you have any questions.
