### ISSUE TITLE
XML Site Map Bugs

### ISSUE THREAD

**Issue by luxurypropertyagent** [semperfiwebdesign/all-in-one-seo-pack#1554]
XML sitemap bugs:
1. When adding another url
Example: Wordpress site location www.page.com/blog/
You would like to add URL www.page.com
appears on xml sitemap as: www.page.com/blog/www.page.com

**Comment by arnaudbroes** [comment]
This is a development repository, not a support forum. You can contact us here - https://semperplugins.com/contact/

**Comment by michaeltorbert** [comment]
One way around this could be that if the additional page is a full URL, we could simply just add it.

**Comment by contactashish13** [comment]
I believe the additional pages feature is supposed to work for both relative as well as absolute URLs. By definition, absolute URLs should be specified with the scheme. I think if we add a comment to the section that tells users to prefix absolute URLs with http(s):// , it should remove the confusion and the bug.

**Comment by wpsmort** [comment]
I tested this and confirmed that you can enter an absolute URL as long as it has the protocol prefix.  I'll amend the inline help text and the documentation to make this clearer.

**Comment by wpsmort** [comment]
@contactashish13 We still need to fix this so that our code checks whether an absolute URL is being entered.  i.e. if test.com or www.test.com is entered then this is an absolute URL and we should treat it as such in the sitemap.

**Comment by contactashish13** [comment]
@wpsmort if the URL entered is of the below format, both will be considered absolute because of the presence of a dot before the first /. I think it would be best to force users to add the protocol no matter what. What do you think?

1. this.is.com/blah/blah/blah (absolute)
2. this.is.a/test.page/ (relative)

**Comment by michaeltorbert** [comment]
> force users to add the protocol

Agreed.
The only issue now is how to handle values already in the database.

**Comment by contactashish13** [comment]
we can assume that presence of a dot before the first / indicates absolute URLs?

**Comment by michaeltorbert** [comment]
well we could probably just use something built in like wp_http_validate_url()

**Comment by contactashish13** [comment]
for stuff already in the db, if it does not pass wp_http_validate_url() then we assume that presence of a dot before the first / indicates absolute URLs and we add the protocol/scheme

**Comment by michaeltorbert** [comment]
I hate to make changes like that, or do you mean do it on the fly?

**Comment by contactashish13** [comment]
yes, on the fly 

1. when the sitemap is being shown
2. when the settings are being shown

**Comment by michaeltorbert** [comment]
When the settings are being shown will be a tough one, and maybe isn't really necessary.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1830

**Comment by wpsmort** [comment]
@contactashish13 This PR changes the behavior of the Page URL field in the Additional Pages section by removing the ability to enter relative URLs  Is there no way to support relative URLs as well as absolute URLs?

**Comment by contactashish13** [comment]
@wpsmort this is as per https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1554#issuecomment-374076114

**Comment by wpsmort** [comment]
@contactashish13 To clarify, my comment https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1554#issuecomment-412619275 was a question.  As I'm not familiar with wp_http_validate_url() I was asking if it was possible to allow relative URLs or not.

I tested the PR and found two instances where I can enter invalid URLs: 

1). Enter the URL without slashes, i.e. http:test.com and hit enter instead of clicking on the Add URL button

2). Enter the URL with only one slash, i.e. http:/test.com and hit enter instead of clicking on the Add URL button

In both cases it adds the URL and it also seems to wipe any other URLs from the database.  Let me know if you cannot reproduce this.

**Comment by contactashish13** [comment]
@wpsmort I feel it does not make sense to allow users to input relative URLs when the sitemap ought to contain absolute URLs only. 

As for URLs already existing in the database, I have tried to deduce whether they are absolute or relative. Can you please try a few random examples and let me know if the logic fails somewhere?

I have fixed the issue you reported above.

**Comment by wpsmort** [comment]
@contactashish13 I tested all variations of absolute and relative URLs.  The only ones that were a problem for URLs already in the database were these examples:

http:domain.com - This was output as http://aioseop1554.local/domain.com
http:/domain.com - This was output as http://aioseop1554.local/domain.com

Is there anything you can do to correctly sanitize these when they are output?

**Comment by contactashish13** [comment]
@wpsmort added support for these types as well
