### ISSUE TITLE
error in woocommerce product 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1671]
Warning: count(): Parameter must be an array or an object that implements Countable in /app/public/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php on line 2640
--

<img width="1094" alt="screen shot 2018-04-26 at 2 39 32 pm" src="https://user-images.githubusercontent.com/17364998/39325653-c1198f02-4960-11e8-9d3c-5544bfe3ebc3.png">

**Comment by wpsmort** [comment]
From Matt Robinson:

I'm getting an error logged from AIOSEO as follows: 

PHP Warning: count(): Parameter must be an array or an object that implements Countable in 
/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 2685 

I've put in a guessed patch on the line before changing it to: 

if ( ! empty( $query->posts ) && is_object( $query ) ) { 

But thought you might like to know about this and have a look yourselves. 

Matt

**Comment by mattyrob** [comment]
Just to confirm that my above, guessed fix - doesn't work. I'll post more after some more investigating.

**Comment by arnaudbroes** [comment]
I'm certain this was happening because of the `$posts = new WP_Query();` line he had in his static PHP page as this notice could only have been thrown if `$query->posts` on line 2684 contains something other than an array.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/8b5b6308a5685744f8edd07fded745d8a441c212/aioseop_class.php#L2415-L2426
