### ISSUE TITLE
UI - Add option to disable animations or make transition better

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1715]
One of our users (Thomas - via email) reported that he occasionally suffers from motion sickness due to the animations that occur when he switches between the SEO and Social Meta tabs. He asked us whether we'd consider adding a setting to turn them off.

[edited by Michael to remove Thomas' email address]

**Comment by michaeltorbert** [comment]
I think this is a great idea. We should probably at a minimum have a way to disable it, even better would be to find a different transition that would make it more accessible for people who may have motion sickness issues.

Someone can feel free to dive into the javascript and come up with something better.

**Comment by contactashish13** [comment]
I've made this use fadein/fadeout instead of show/hide. In medium vs. slow fade, I find slow more graceful.

PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2271

I see that we are using a bespoke implementation of tabs where as now we can use https://jqueryui.com/tabs/ as jqueryui is being used extensively in other parts of the plugin as well. Eventually, tabs should also make it to the main settings page where each module is a tab than a separate menu item.

@EkoJR @arnaudbroes @wpsmort suggestions?

**Comment by arnaudbroes** [comment]
I'm all for switching custom code to framework code. As for the settings, I agree we should move all modules to a single settings page at some point.

**Comment by wpsmort** [comment]
@contactashish13 I've opened #2274 for implementing jQuery Tabs and assigned it to you for this release.  We already have #127 open for your suggestion of using tabs on the main settings screens but that will be done in a future release.

**Comment by michaeltorbert** [comment]
Does https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2274 make this issue obsolete?

**Comment by michaeltorbert** [comment]
Let's reach out to Thomas and see if it's resolved for him.

**Comment by arnaudbroes** [comment]
I've reached out to Thomas today.

**Comment by arnaudbroes** [comment]
Here's what Thomas said (although he no longer uses AIOSEOP):

> If it’s still an animation – as opposed to simply switching – the likelihood of it triggering a spell of dizziness and nausea remains.

**Comment by michaeltorbert** [comment]
Closing as only one person has reported it.
