### ISSUE TITLE
article:published_time and article:modified_time changed to UTC in 2.6

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1724]
In https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1450 for 2.6, we made a change so the the sitemap's post times were UTC. 
Now it's reported that this change is incorrectly applying to post meta as well. Reported here: https://wordpress.org/support/topic/after-last-update-the-published-and-modified-time-has-changed/

We should revisit this and a) verify the new bug reported and b) if verified, that 1450 broke it, and c) discuss whether we're handling #1450 right to begin with (possibly its own issue).

**Comment by wpsmort** [comment]
@michaeltorbert This is correct and was an intentional change to those two Open Graph meta tags.  Prior to v2.6, those date/time stamps were being output as UTC ( a Z on the end indicates UTC time) but the time was not in UTC but instead the time was local time.  #1450 fixed this by changing those date/time stamps to UTC time.

This is not a bug, it's an intentional change to fix a reported problem.

**Comment by wpsmort** [comment]
Additional detailed explanation:

All in One SEO Pack outputs two meta tags for use by Facebook when the Facebook Object Type is set to Article.  These meta tags are:

article:published_time
article:modified_time

Prior to v2.6, All in One SEO Pack showed that these date/time stamps were in UTC. This was done by outputting a Z on the end of the time as follows:

2018-06-06T22:20:02Z

However, the time we output was actually the local time of the users WordPress install.  So for us the time would be in Eastern US time.  Therefore, we were incorrectly reporting that the time was UTC and the time did not match the times output by WordPress.  This bug was reported in #1450.


We had two options - 1). We could change the time we output so that it was converted to UTC, or 2). We could output the correct timezone offset, i.e. 2018-06-06T18:20:02-04:00

We chose option 1 so that all times would be output correctly as UTC and would match the date/time stamp output by WordPress.

These meta tags are only used by Facebook (https://developers.facebook.com/docs/reference/opengraph/object-type/article/) and should not affect anything as they are now correctly output to match the date/time stamp output by WordPress for published date and updated date.
