### ISSUE TITLE
Can not edit Robots.txt

### ISSUE THREAD

**Issue by Foxer2018** [semperfiwebdesign/all-in-one-seo-pack#1802]
Good afternoon!
I can not edit Robots.txt in the "File Editor" section. There is edited only. Tell me what could be the problem. Is it possible that this is not a revision of this version?

**Comment by arnaudbroes** [comment]
@Foxer2018 The File Editor module is meant to edit the .htaccess file. You can use the Robots.txt module for that purpose. Please note that this is not a support forum, but a development repository, which is why I'm closing this issue. If you require any additional support from us, please purchase a license here - https://semperplugins.com/all-in-one-seo-pack-pro-version/
