### ISSUE TITLE
Consider removing "Run shortcodes in description" setting

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1846]
Do we still need this? It causes a lot of bugs with other plugins (like page builders) and I can't think of what purpose this has.

**Comment by wpsmort** [comment]
@arnaudbroes Yes, this is still needed.  The history behind this option is that we added when theme builders because popular.  Many theme builders such as Fusion Builder use shortcodes to control the layout of the page.  We have to run these shortcodes in order to extract the content for the autogenerated descriptions.  This setting is really meant for anyone using these theme builders.

**Comment by EkoJR** [comment]
I was curious if it was possible to change the format, rather than remove?

I was also curious, what's the history/reason for not using shortcode brackets `[` and `]`? I imagine there may have been some conflicts when theme builders would add their shortcode content, and possibly stripping shortcodes before having a chance to process.

With shortcodes, I speculate the big problem was shortcodes with the same name. Which brings me to wonder, why not use `[aioseop field="blog_title"]`?

With the unique character, could there possible be a safer character or string than the current method, ex. `%blog_title%`?

**Comment by michaeltorbert** [comment]
@EkoJR Offhand I'd say everything in your comment is great, but switching to that now many not be possible...

**Comment by arnaudbroes** [comment]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2488 could be a solution where we just keep adding shortcodes that are known to conflict to the funtion I've introduced.

**Comment by Garconis** [comment]
Please do not consider removing shortcode functionality in the auto-generated descriptions. In fact, please consider this issue (https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1867), and allow shortcodes to function properly when added to the page's Title and Description.

**Comment by arnaudbroes** [comment]
@Garconis we've implemented a fix for conflicting shortcodes in our latest 3.0 version (https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2488) so we won't be removing them. As for the other issue, we're going to consider adding it when we've finished fixing any bugs 3.0 introduced and start working on 3.1, which shouldn't be too long from now.

I believe this issue can be closed.
