### ISSUE TITLE
Issue/PR protocol

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1884]
We need more consistency in handling issues and PRs. Which gets assigned to whom, where do comments go, etc.
Once we've discussed this and have agreed on what to do, we should make a spot in the github wiki for it.

My initial thoughts:

- The issue is assigned to, if anyone, the person who "owns" the issue and is responsible for making sure it progresses to a resolution.
- The  PR is assigned to whomever is working on the PR at that time (development, testing, code review, etc).
- Comments  about the issue itself should be on the issue.
- Comments about the code should be on the PR. (I realize there's some gray area between these last two).

**Comment by wpsmort** [comment]
I agree with your thoughts on this, especially about where comments should go as there's been discussion and confusion over this.

The issue should remain with the owner and be labeled according to what the issue is for (Bug, Enhancement, etc) and priority.  

The PR should change hands as it progresses through development, testing, etc. and be labeled with the stage in development and priority.  I strongly feel that comments to do with testing should be in the PR.  If a problem is identified during testing then the steps to reproduce should be there and we should be able to see that a commit follows which resolves the problem.

**Comment by contactashish13** [comment]
Assuming there is always one PR per issue, the comments should be on the issue even if they pertain to the PR because the PR has no existence of its own without the issue. Often the comments on the PR pertain not just to the testing but also an additional scenario (e.g. how to replicate a specific scenario that has been missed after a PR has been submitted for review) and or code samples (e.g. the two filters that I had added). It just makes it hard for anyone in the future to follow the issue, use the code samples or understand the use case behind the issue/PR. 

Comments on specific lines of the code would obviously need to be in the PR but they would be added as comments against specific lines and not be a general comment on the PR.

I would agree with generic comments in the PR if and only if an issue can have multiple PRs but that is not the case.

**Comment by EkoJR** [comment]
Another problem I've seen happen from time to time is conversations or comments that hold no future value to someone else who would be working it. Most times, it's just others outside the dev team trying to weigh in on issues; or creating their own issue. However, there have been a few times information had to get chased down, and maybe it would help to add something about Slack (and/or returning to issue with helpful info to add, or comment regarding the conversation).

Issue

*   Assignee: Should remain with assigned person, unless someone else is leading a PR for it.
    *   ??? What about for cases when no one is working on a task? Could be created by someone else (usually closed anyways), abandoned, or stale. 
*   Reproducing the issue.
*   Line comment: If it is old. (This one is a bit of a grey area, and sometimes is just referencing code).
*   If possible, helpful info regarding a conversation; sometimes it's just a status.

PR

*   Assignee: Changes according to Current Person working on it.
*   Reproduce PR issue – Usually new issues being produced, but if issue exists without PR, then make sure to add to Issue as well.
*   Line Comment: If it is new.
*   Code Review.
*   Conflicts with code.
    *   Merge conflict.
    *   Concept conflict – This varies, could be a possible-conflict with another PR, deprecated operations.

Slack

*   Asking about a status of an issue or PR.
*   Credentials & private information is obviously held privately or in a closed group.

**Comment by michaeltorbert** [comment]
In my mind, comments on the Github issue should be about the overall "issue" itself. Comments like https://github.com/semperfiwebdesign/aioseop-pro/pull/377#issuecomment-416762702 make no sense in the issue, and are only relevant to the PR. Just my $.02

**Comment by contactashish13** [comment]
@michaeltorbert can we reach a final conclusion so that everyone can follow the same protocol?

**Comment by michaeltorbert** [comment]
@contactashish13 I've created a page listing each of our preferences. https://github.com/semperfiwebdesign/all-in-one-seo-pack/wiki/Issue-PR-Protocol

This isn't for me to make a unilateral decision on, we should discuss and come to a consensus. A short call at some point may make sense.

**Comment by arnaudbroes** [comment]
I've added my input to that draft page. I feel like there's pretty a much a general consensus.

When we decide on a final protocol, everyone should carefully follow all steps each time they add an issue/PR to avoid going back and forth with each other all the time. 

I also think it wouldn't be a bad idea to make someone responsible for our GitHub workflow. This person should review the GitHub repository on a bi-weekly/monthly basis and assign/clean up issues where necessary.

**Comment by michaeltorbert** [comment]
@arnaudbroes Sounds like you volunteered to be that person. ;)

**Comment by michaeltorbert** [comment]
I think we've reached a pretty good process, so I'm closing this.
Anyone can feel free to reopen.

**Comment by arnaudbroes** [comment]
I'll still create documentation for this in the GitHub wiki at some point but I agree that this can be closed.

**Comment by michaeltorbert** [comment]
You should open an issue for that then.
