### ISSUE TITLE
Conflict with Divi Child Theme

### ISSUE THREAD

**Issue by paintbox** [semperfiwebdesign/all-in-one-seo-pack#1948]
Hello
http://www.monteltham.com.au
WordPress 4.9.8 running Divi Child Theme
When All In One SEO Pack v 2.8 is activated I am unable to edit any pages.
When turned off I can edit my pages
Thoughts?
I can give you access if this helps
Regards
William Wakefield
william@cairnsdesign.website
--

**Comment by arnaudbroes** [comment]
@paintbox I'm unable to replicate this issue using the latest version of All in One SEO Pack, the Divi theme and the Divi Builder plugin. Please provide us with steps to replicate this issue or follow these steps to narrow down the issue - https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

If this issue is specifically caused by your custom child theme, then we won't troubleshoot this issue unless you have a support license. If you do not have a support license, but would like to purchase one, then you can do so here - https://semperplugins.com/all-in-one-seo-pack-pro-version/
