### ISSUE TITLE
Use original keywords entered by user

### ISSUE THREAD

**Issue by toxpal** [semperfiwebdesign/all-in-one-seo-pack#1949]
Just migrated from Yoast to AIO on 2 websites, works great. The only thing I don't understand is why plugin alters meta keywords (entered by user) by removing space symbols and uppercase letters. Let's say I enter such keywords for page:

`Lexus cars in Japan, Honda services in China, Whatever`

The plugin saves keywords correctly and keywords are displayed exactly like this in administration dashboard. However, they are displayed like this in source code of page (which is served to search engines and visitors):

`lexus cars in japan,honda services in china,whatever`

Notice how all space symbols between keywords were removed and each word was converted into lowercase. I realize it might have no effect in rankings, but it just looks wrong in source code, especially when using brand names, country names, or similar stuff in keywords. What's the logic behind this conversion?

P.S. Like I said, keywords are NOT altered in administration dashboard, they always remain original (which is good, of course).

P.P.S. If this has already been discussed, please accept my apologies and just drop me a link. I did a search before submitting issue, and didn't find such ticket.

**Comment by arnaudbroes** [comment]
Off the top of my head, I'd say this was done purely from a developer's perspective. One whitespace character means one extra byte in the source code. Typically, any decent HTML parser will remove redundant white spaces. In any case, I would recommend against spending time on entering meta keywords since these no longer carry any weight at all. Most search engines no longer consider them, and some even penalize you if you abuse the tag (as it's considered a spam signal).
