### ISSUE TITLE
Maximum execution time exceeded in v2.9

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#1997]
**Describe the bug**
This instance occurred while editing/saving a post. However, xDebug profiler found other instances where sitemaps are being built.
```
( ! ) Fatal error: Maximum execution time of 120 seconds exceeded in C:\WebProjects\aioseop\WordPress\wp-includes\wp-db.php on line 1924
Call Stack
#	Time		Memory		Function								Location
1	0.8174		409552		{main}( )								...\post.php:0
2	0.8391		410304		require_once( 'C:\WebProjects\aioseop\WordPress\wp-admin\admin.php' )	...\post.php:12
3	4.5545		7212048		do_action( )								...\admin.php:156
4	4.5545		7212424		WP_Hook->do_action( )							...\plugin.php:453
5	4.5545		7212424		WP_Hook->apply_filters( )						...\class-wp-hook.php:310
6	4.7323		7344392		AIOSEOP_Updates->version_updates( )					...\class-wp-hook.php:286
7	4.7336		7344392		do_action( )								...\aioseop_updates_class.php:50
8	4.7336		7344768		WP_Hook->do_action( )							...\plugin.php:453
9	4.7336		7344768		WP_Hook->apply_filters( )						...\class-wp-hook.php:310
10	4.7336		7345784		All_in_One_SEO_Pack_Sitemap->do_sitemaps( )				...\class-wp-hook.php:286
11	4.7336		7345784		All_in_One_SEO_Pack_Sitemap->do_indexed_sitemaps( )			...\aioseop_sitemap.php:1474
12	116.0900	23201728	All_in_One_SEO_Pack_Sitemap->do_write_sitemap( )			...\aioseop_sitemap.php:1871
13	116.0900	23201728	All_in_One_SEO_Pack_Sitemap->do_build_sitemap( )			...\aioseop_sitemap.php:1828
14	116.0900	23201728	All_in_One_SEO_Pack_Sitemap->get_sitemap_data( )			...\aioseop_sitemap.php:1801
15	116.0901	23201728	All_in_One_SEO_Pack_Sitemap->get_all_post_priority_data( )		...\aioseop_sitemap.php:1356
16	117.5885	35354432	All_in_One_SEO_Pack_Sitemap->get_prio_from_posts( )			...\aioseop_sitemap.php:3244
17	119.9388	28689784	All_in_One_SEO_Pack_Sitemap->get_images_from_post( )			...\aioseop_sitemap.php:2958
18	119.9917	28698432	aiosp_common::get_image_src_for_url( )					...\aioseop_sitemap.php:3109
19	119.9928	28700088	wpdb->get_var( )							...\aiosp_common.php:201
20	119.9928	28700360	wpdb->query( )								...\wp-db.php:2380
21	119.9934	28682560	wpdb->_do_query( )							...\wp-db.php:1813
```

**To Reproduce**
1. (Possibly) Create many posts (this instance occurred at 1800+ posts).
    1. Make sure to have images added.
2. Activate XML Sitemap.
3. Make sure "Dynamic Sitemap" is unchecked in AIOSEOP > Sitemap XML.
4. Go to post to edit.
5. Click on Click save.

Another possible scenario.
1. Go to Sitemap settings.
2. Click save settings.

**Expected behavior**
The instance should continue to operate.

**Version Info (please complete the following information):**
 - WordPress version: 4.9.8
 - All in One SEO Pack version: 2.9
 - PHP version: 7.2
 - PHP max_execution_time = 120 seconds
 - PHP memory_limit = 128M

**Comment by wpsmort** [comment]
Possible related report from Alex Col by email.

Alex reported that his site was very slow after updating to AIOSEOP v2.9.  He stated that the slowness was on the backend and the frontend and was resolved when he deactivates AIOSEOP.  He said the problem typically occurs 2 minutes after activating AIOSEOP.  I got access to his site and found that it has over 151,000 posts and 62,000 media items.  I did see occasional performance issues when navigating around the back end of the site.  I saw no performance differences on the front end with AIOSEOP active or deactivated.  

He had the XML Sitemap module activated but not the Open Graph module.  The XML Sitemap took an extremely long time to load.  He had Sitemap Indexes enabled but pagination was set to 300 and he was including Media Attachments.  I excluded Media Attachments and set the pagination to 1000 and this resolved the issue with the sitemap taking a long time to load.  

I discussed this with @EkoJR to see if this was consistent with what he is seeing.  Ben thinks that this could be caused by the get_image_src_for_url() function which was added in v2.9 (PR #1350).  This function queries the postmeta table and he thinks that this query could be resource heavy especially on large sites.  The function is used to get the full size image for the OG image (#260) and for the sitemap (#1202).  Ben is going to do more testing, look at whether we can get the full size image in a different way, and speak to @contactashish13 to see why he used this approach.

If we get any other reports of 500, 502 or 504 errors or slow or unresponsive sites we should look to see if deactivating the XML Sitemap module and Open Graph module resolves the problem.

**Comment by contactashish13** [comment]
The method `get_image_src_for_url` is used to 

1. determine `attachment id` of an image url
2. use that `attachment id` to get the full size image

This could be a problem because it runs once for every post that is being processed. This is probably made worse when someone has selected `First Image in Content` for Social Meta or is using the sitemap option as both scan through the entire post content to fetch images. 

I believe the problem is because the query runs for any image url, whether local or external. I can make this more efficient to only look at `local` images but I will need a test instance to verify if it works. @wpsmort could you help in this?

**Comment by arnaudbroes** [comment]
Looking at that get_image_src_for_url() function, I'd say it's likely that query is causing problems if it needs to be executed so frequently. We should probably revert the code to get a fix out and think of a different approach in the meantime if it's going to take too long to improve this.

**Comment by EkoJR** [comment]
I'm leaning towards reverting this as well. I've tried a few possible fixes, but it is still very taxing on the server (with timeouts). I thought about minimizing it to 1 query, but it still needs to search for other URLs.

It becomes increasingly worse the more content and post meta there is on a site. Best bet is to minimize querying the SQL, especially searching in post_meta.

**Comment by michaeltorbert** [comment]
@contactashish13 Are you opposed to reverting for the time being until we come up with something better?
@EkoJR 
If so, can one of you submit a PR to revert for now?

**Comment by contactashish13** [comment]
I would prefer to address the issue than revert, unless that is the only option left or we are short on time. Whatever is the consensus.

**Comment by wpsmort** [comment]
@contactashish13 We are on a short timeframe here, it's potentially breaking users sites and we're receiving a lot of complaints and higher than normal support volume.

**Comment by michaeltorbert** [comment]
@contactashish13 

We've had many people complaining of this breaking their site, which means potentially tens of thousands or more have broken sites.
We need to release something that stops their sites from breaking ASAP today, and then work on addressing the issue.

**Comment by wpsmort** [comment]
@kuse-de Can you check the SEO for Custom Post Types setting in All in One SEO Pack > General Settings > Custom Post Type Settings to see if that is enabled or disabled.  Most of the reports we've received about titles and descriptions missing are because that setting got disabled.  Enabling is and ticking the appropriate checkboxes next to the Post Types you want to use All in One SEO Pack for fixes the problem for most users.  

As far as the memory issue goes, please can you try deactivating the XML Sitemap and Open Graph modules in Feature Manager and see if that resolves the memory issue.   This would help us a lot in confirming this bug.

**Comment by michaeltorbert** [comment]
@EkoJR Are we building the sitemap on every post save even if it's dynamic?

**Comment by kuse-de** [comment]
@wpsmort this didnt fix it for me but i noticed that my issue is related to gantry framework plugin, i will open a new issue for that
