### ISSUE TITLE
Disappearing SEO meta section in 2.9.x

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2029]
Reported by _many_ people.

Steps to reproduce:
1) Install 2.8. 
2) Check posts and pages under SEO for Custom Post Types (Content Types in 2.9)
3) Disable "SEO for Custom Posts Types" radio.
4) Verify that the SEO meta section appears in wp-admin for edit posts and on the post/page on the front-end.
5) Update to 2.9.
6) SEO meta section disappears.
7) Enabling SEO for Content Types makes them reappear.

We should investigate what in 2.9 caused this behavior to change. I suspect it has something to do with the addition of is_seo_enabled_for_cpt() but someone should confirm this.

First, we need to determine conclusively what change in 2.9 caused this behavior change.

Second, we need to decide what to do. My .02 is that we simply remove "SEO fo Content Types" and just have the check boxes. https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2028
This would require going through all uses of the aiosp_enablecpost option and adjusting as needed.

**Comment by contactashish13** [comment]
I can confirm its because of that method. If I return true, the meta is shown.

If the radio button `disabled` is checked, does that not mean that no meta should show and therefore the behavior is correct?

To continue with previous behavior, we have 2 options 
- remove the radio buttons unless they serve any other purpose besides toggling the view in the settings screen
- make https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L3868 an `OR` conditions instead of an `AND` viz.

```
return 'on' === $aioseop_options['aiosp_enablecpost'] || in_array( get_post_type(), $aioseop_options['aiosp_cpostactive'], true );
```
instead of
```
return 'on' === $aioseop_options['aiosp_enablecpost'] && in_array( get_post_type(), $aioseop_options['aiosp_cpostactive'], true );
```

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/problems-with-home-page-settings/

After getting a login for the users site, I found that SEO for Custom Post Types was disabled.  Enabling it rectified the problem.

**Comment by contactashish13** [comment]
@wpsmort can you please comment on my observations?

**Comment by wpsmort** [comment]
@contactashish13 To answer your first question: 

Yes, if SEO for Content Types is set to Disabled, no SEO meta should be output.  This was the change we made in v2.9 (see #1069).  However, it led to unforeseen consequences because prior to v2.9 we were outputting SEO meta when that was disabled.  Changing this to the correct behavior resulted in lots of users reporting that SEO meta was no longer being output.  

The best solution would be to remove this option, we have issue #2028 to discuss this and everyone agrees we should remove it.
