### ISSUE TITLE
Add option to set the defaults for NOINDEX and for custom taxonomies

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#204]
Add option to set the defaults for NOINDEX and for custom taxonomies

**Comment by arnaudbroes** [comment]
@wpsmort do you have any idea what this means and if we do not have it already?

**Comment by wpsmort** [comment]
@arnaudbroes I'm not entirely sure I understand what this issue is about.  If it's for adding an option to se Noindex for custom taxonomy archives then we already have that (https://semperplugins.com/documentation/noindex-settings/#use-noindex-for-the-taxonomy-archives).  

As to what "set the defaults for Noindex" means, I have no idea on that.  

If you don't remember what this was about then I'd say close the issue.

**Comment by arnaudbroes** [comment]
This is one of many issues I copied from a spreadsheet you had before we migrated to GitHub, so since you don't remember what it is for I'll just go ahead and close this.
