### ISSUE TITLE
add wc tested and required versions

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2043]
Basically we add the following to the main plugin file:

* WC requires at least: x
* WC tested up to: y

source: https://docs.woocommerce.com/document/create-a-plugin/#section-8

**Comment by arnaudbroes** [comment]
https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/
I'll check how this looks like atm.

**Comment by michaeltorbert** [comment]
@arnaudbroes See if you can figure out the advantages and disadvantages of doing this. What does it look like if we haven't updated yet?

**Comment by arnaudbroes** [comment]
When it has not been tested up to the latest version:
![image](https://user-images.githubusercontent.com/18156697/57391963-9673a700-718d-11e9-8e43-e43ddab00055.png)

When it has been tested up to the latest version:
![image](https://user-images.githubusercontent.com/18156697/57392027-bc994700-718d-11e9-9988-f93256045efa.png)

I don't see any advantages in this; only a disadvantage since we'd have to keep track of WooCommerce releases.

**Comment by michaeltorbert** [comment]
Yeah I don't see any point to this.
