### ISSUE TITLE
Regular release schedule + releasing RCs 

### ISSUE THREAD

**Issue by contactashish13** [semperfiwebdesign/all-in-one-seo-pack#2114]
We may want to look into 

- making a regular release schedule e.g. on the 2nd Wednesday of every month as this would benefit users knowing we have a regular schedule instead of our current irregular method. This would also benefit us by not pushing everything possible into one release and thereby causing am implosion (like in 2.9). 
- releasing RCs before full fledged releases so that things can be tested by the brave/closed user group  

Comments/suggestions are welcome.

**Comment by wpsmort** [comment]
@contactashish13 I'm all in favor of having a release schedule as you suggest.

**Comment by EkoJR** [comment]
I would be partially in favor, and would lean more towards **Quarterly Releases** for major versions; since that seems to be roughly how often we've released versions.

I believe there are other things that should be addressed; primarily with workflows. Implementing some form of Scrum might naturally cause the team to be more organized as a whole, and setting up an Agile workflow might also make things more efficient as a team (which we do try to use).

**Comment by michaeltorbert** [comment]
I agree wholeheartedly with @contactashish13's suggestions. 

@EkoJR The problem with quarterly releases is that we'd be packing too much into each release, opening us up to more bugs than with more frequent releases, such as monthly.
I've not participated in scrum or agile workflows, what aspects of those do you think would help?

**Comment by arnaudbroes** [comment]
I'm in favour of working with Scrum, but we'll need to come up with a good strategy to make it work because besides Steve and Michael we're all freelancers with shifting availibility and different time zones. 

@michaeltorbert stuff like daily standups are obviously things we're not able to effectively implement, but working with sprints (ideally biweekly or monthly ones) might be a big step forward. 

I've been working quite a bit on unit testing during my internship and I'd say that's something we need to spend more time on sooner than later. I know Ashish did some work on it some time ago, but I'm not sure whether we run them before each release. Regardless, we should have a unit test for every feature of the plugin so we can avoid releases that break more than they fix.

Our releases shouldn't be big,  but they need to be qualitative. I'm not blaming anyone since I hardly have anything to do with the development of the plugin but even I can see that we've been patching up holes in the ship more than anything else this year.

**Comment by EkoJR** [comment]
@michaeltorbert Between major and minor version releases, I was trying to refer to major version releases. Which may have been interpreted as in general. Monthly releases would be good, just some worry it may rush updates as an affect.

I was leaning towards bi-weekly for Scrum. It's essentially the development team discussing reports and planning. Giving everyone a better idea which tasks to handle. 

Some Scrums can be split up into groups; like Sales, Support, and Development teams. Possibly with each having their own talking point structure; could be concerns, what's been done, what next on the Todo list, ideas, type of bugs to squash, etc. Could start it as a basic meeting, but I think we need some form of structure on what to bring to the meeting.

**Comment by arnaudbroes** [comment]
@EkoJR  I agree on bi-weekly updates, and I also like your idea to split up scrums into different teams. The idea is not to rush anything though. We release whatever code is finished and tested properly and anything else transfers onto the next sprint.

**Comment by wpsmort** [comment]
I'm not sure we have a need to split Scrums into groups.  We have such a small team, and our focus is on development, that we should just need one group.  Your suggestion of bi-weekly updates is good.

**Comment by michaeltorbert** [comment]
continuing this in slack...
