### ISSUE TITLE
Issue with home page title and description

### ISSUE THREAD

**Issue by MarcoVitale** [semperfiwebdesign/all-in-one-seo-pack#2223]
Hello, since updating to Wordpress 5.0.3 and All-in-one SEO Pack 2.12 the title and description fo the home page of my website are messed up (the Google's result shows some japanese charachters and other random stuff about Kalvin Klein Jeans which I have no idea where it comes from).
Moreover, it is impossible to access the plugin's dashboard or settings, it just shows a broken page.
However the information in the fields below the pages are correct (title, description, etc.)
Any ideas or suggestions on how to solve? 
Thanks
![image](https://user-images.githubusercontent.com/25329178/53180932-ddbeb280-35f6-11e9-950a-dd0a252c14d8.png)

**Comment by wpsmort** [comment]
@MarcoVitale This is not caused by All in One SEO Pack.  This looks like it's a malware infection.  You can check this by typing site:studentinfo30.com into Google.  If you then look at Google's cache for your homepage you'll see you get this content - http://webcache.googleusercontent.com/search?q=cache:4E-HbRe25rYJ:studentinfo30.com/+&cd=1&hl=en&ct=clnk&gl=us.  You should check your site and server for malware.

**Comment by MarcoVitale** [comment]
@wpsmort thanks a lot for your advice. Do you have any suggestion on helpful plugins to check the site for malware?

**Comment by michaeltorbert** [comment]
Sucuri or Wordfence

**Comment by MarcoVitale** [comment]
@michaeltorbert cheers, will try!
