### ISSUE TITLE
Text alignment in 3.0 branch

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2284]
@arnaudbroes @wpsmort @EkoJR  Was this intentional or did we break something?

<img width="382" alt="Screen Shot 2019-03-11 at 8 51 55 PM" src="https://user-images.githubusercontent.com/17364998/54168458-f3303b00-4444-11e9-8fde-9867950e79d6.png">

**Comment by arnaudbroes** [comment]
Not intentional as far as I know.

**Comment by wpsmort** [comment]
This was unintentional and looks like it may have been caused by the tooltips PR #2236.

**Comment by EkoJR** [comment]
I believe this may have been intentional to some degree. I can't remember the exact reason, and can't find any mention of the change in old PRs. Either way, this will probably have to be restored if there is no reason for the change.

Many of the style changes did occure here https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1814

**Comment by EkoJR** [comment]
Actually, this wasn't from the changes in PR #2236, but rather changes that did not occur. I vaguely remember some mention of it in the past to fix it, and thought it may have been added.

Although, this looks like a mixture of changes/issues that occured over time since when the PR was created.
