### ISSUE TITLE
google web structure problem

### ISSUE THREAD

**Issue by qasimsaleem1** [semperfiwebdesign/all-in-one-seo-pack#2310]
Google webstructure problem??

**Comment by wpsmort** [comment]
There is no information as to what this bug is or what feature is being requested.  When creating a new issue, you must select the correct issue type and complete all information requested in the form:

Bug Report - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new?assignees=&labels=&template=bug_report.md&title=
 
Feature Request - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new?assignees=&labels=&template=feature_request.md&title=
