### ISSUE TITLE
Google does not read all sitemap index files

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2554]
Reported here: https://wordpress.org/support/topic/sitemap-error-67

> usually i set sitemap with 1000 reference inside and it generate N file. I see all file… but google nor read all but only the first…

> All in One Seo Pack will generate this SITEMAP: https://www.lucianoblancato.it/sitemap.xml

with this

URL	Last Change
https://www.lucianoblancato.it/sitemap_addl.xml
https://www.lucianoblancato.it/sitemap_post.xml
https://www.lucianoblancato.it/sitemap_page.xml
https://www.lucianoblancato.it/sitemap_attachment_1.xml
https://www.lucianoblancato.it/sitemap_attachment_2.xml
https://www.lucianoblancato.it/sitemap_attachment_3.xml
https://www.lucianoblancato.it/sitemap_attachment_4.xml
https://www.lucianoblancato.it/sitemap_attachment_5.xml
https://www.lucianoblancato.it/sitemap_attachment_6.xml
https://www.lucianoblancato.it/sitemap_attachment_7.xml
https://www.lucianoblancato.it/sitemap_attachment_8.xml
https://www.lucianoblancato.it/sitemap_attachment_9.xml
https://www.lucianoblancato.it/sitemap_attachment_10.xml
https://www.lucianoblancato.it/sitemap_robo_gallery_table.xml
https://www.lucianoblancato.it/sitemap_archive.xml
https://www.lucianoblancato.it/sitemap_author.xml
https://www.lucianoblancato.it/sitemap_category.xml
https://www.lucianoblancato.it/sitemap_post_tag_1.xml
https://www.lucianoblancato.it/sitemap_post_tag_2.xml
https://www.lucianoblancato.it/sitemap_post_tag_3.xml
https://www.lucianoblancato.it/sitemap_post_tag_4.xml
https://www.lucianoblancato.it/sitemap_post_tag_5.xml
https://www.lucianoblancato.it/sitemap_post_tag_6.xml
https://www.lucianoblancato.it/sitemap_post_tag_7.xml
https://www.lucianoblancato.it/sitemap_post_tag_8.xml
https://www.lucianoblancato.it/sitemap_post_tag_9.xml
https://www.lucianoblancato.it/sitemap_post_tag_10.xml
https://www.lucianoblancato.it/sitemap_post_tag_11.xml
https://www.lucianoblancato.it/sitemap_post_tag_12.xml
https://www.lucianoblancato.it/sitemap_post_tag_13.xml
https://www.lucianoblancato.it/sitemap_post_tag_14.xml
https://www.lucianoblancato.it/sitemap_post_tag_15.xml
https://www.lucianoblancato.it/sitemap_post_tag_16.xml
https://www.lucianoblancato.it/sitemap_post_format.xml

Google webmaster tools read only this:

Sitemap
https://www.lucianoblancato.it/sitemap_addl.xml
https://www.lucianoblancato.it/sitemap_archive.xml
https://www.lucianoblancato.it/sitemap_attachment_1.xml
https://www.lucianoblancato.it/sitemap_attachment_10.xml
https://www.lucianoblancato.it/sitemap_attachment_2.xml
https://www.lucianoblancato.it/sitemap_attachment_3.xml
https://www.lucianoblancato.it/sitemap_attachment_4.xml
https://www.lucianoblancato.it/sitemap_attachment_5.xml
https://www.lucianoblancato.it/sitemap_attachment_6.xml
https://www.lucianoblancato.it/sitemap_attachment_7.xml
https://www.lucianoblancato.it/sitemap_attachment_8.xml
https://www.lucianoblancato.it/sitemap_attachment_9.xml
https://www.lucianoblancato.it/sitemap_author.xml
https://www.lucianoblancato.it/sitemap_category.xml
https://www.lucianoblancato.it/sitemap_page.xml
https://www.lucianoblancato.it/sitemap_post.xml
https://www.lucianoblancato.it/sitemap_post_format.xml
https://www.lucianoblancato.it/sitemap_robo_gallery_table.xml

**Comment by michaeltorbert** [comment]
Youtube video https://youtu.be/U5-7X2-m8Do

**Comment by michaeltorbert** [comment]
@wpsmort @arnaudbroes Can anyone decipher what he's trying to say?

**Comment by michaeltorbert** [comment]
> config 1 (with problem)
1. I go to the configuration page and put 1000 in size sitemap
2. will be created a sitemap with a child
3. I insert sitemap url on google
4. google not read all sitemap (child) but only a part (usally 15 but i have 25 child).

for this reason google does not index the whole site but only a part

config 2 (no problem)

1. I go to the configuration page and put 50.000 in size sitemap
2. will be created a sitemap with a child
3. I insert sitemap url on google
4. google read all sitemap (child included).

but with config 2 i have a sitemap heavy with 50.000 record… 🙁 and this is another problem …

**Comment by wpsmort** [comment]
I'm trying to reproduce this with my public site.

**Comment by wpsmort** [comment]
I've been able to reproduce this with my public site which has a sitemap index with 26 sitemaps.  Google only pulls 17 of them when I submit the sitemap.  I've been able to reproduce this with v2.12.1 and an old version 2.5 from last year as well meaning this is not new.  

Google's docs state that they'll accept "up to 500 sitemap index files for each site" (https://support.google.com/webmasters/answer/75712). 

I've tested with two other well known plugins and been able to reproduce the problem with one of them.  It seems to be a problem with the new Google Search Console Sitemaps report. I'm going to see if they pick up all the sitemaps in the index after 12 or 24 hours.

**Comment by daliasued** [comment]
Hi,

I used **Yoast SEO** from the beginning of my project (I didn't know about your plugin LOL), everything runned ok (Yoast), but I bought a new theme for movies and series with post types.

The adjustment in Yoast was Ok to read the post types, but the sitemap doesn't show up for the post type in Google Search Console. I searched for help but nobody answered me. I have Jetpack who has a SEO too, but the same problem, Google Search Console doesn't read anything, they gave me this answer:

"I think I discovered the problem here, in that Jetpack has a problem larger number of items and is creating a sitemap structure that is incompatible with Google webmaster tools right now. I've added your ticket to this public issue here: 

https://github.com/Automattic/jetpack/issues/7828

Right now my suggestion would be to look into other plugins that support custom post types (Actors, Movies, etc). Wish I had a different answer for you."

So I search again and found your plugin, Install bla bla... Enable Sitemap Indexes for 1000, go to Google Search Console, and doesn't read anything just 0.

/sitemap_actor_category.xml.gz	No se ha podido obtener	0
/sitemap_addl.xml.gz	No se ha podido obtener	0
/sitemap_attachment_1.xml.gz	No se ha podido obtener	0
/sitemap_attachment_10.xml.gz	No se ha podido obtener	0
/sitemap_attachment_11.xml.gz	No se ha podido obtener	0
/sitemap_attachment_12.xml.gz	No se ha podido obtener	0
/sitemap_attachment_2.xml.gz	No se ha podido obtener	0
/sitemap_attachment_3.xml.gz	No se ha podido obtener	0
/sitemap_attachment_4.xml.gz	No se ha podido obtener	0
/sitemap_attachment_5.xml.gz	No se ha podido obtener	0
/sitemap_attachment_6.xml.gz	No se ha podido obtener	0
/sitemap_attachment_7.xml.gz	No se ha podido obtener	0
/sitemap_attachment_8.xml.gz	No se ha podido obtener	0
/sitemap_attachment_9.xml.gz	No se ha podido obtener	0
/sitemap_category.xml.gz	No se ha podido obtener	0
/sitemap_film_category.xml.gz	No se ha podido obtener	0
/sitemap_film_country.xml.gz	No se ha podido obtener	0
/sitemap_film_year.xml.gz	No se ha podido obtener	0
/sitemap_haru_actor.xml.gz	No se ha podido obtener	0
/sitemap_haru_film.xml.gz	No se ha podido obtener	0
/sitemap_haru_trailer.xml.gz	No se ha podido obtener	0
/sitemap_haru_video.xml.gz	No se ha podido obtener	0
/sitemap_page.xml.gz	No se ha podido obtener	0
/sitemap_post_1.xml.gz	No se ha podido obtener	0
/sitemap_post_2.xml.gz	No se ha podido obtener	0
/sitemap_post_3.xml.gz	No se ha podido obtener	0
/sitemap_post_4.xml.gz	No se ha podido obtener	0
/sitemap_post_5.xml.gz	No se ha podido obtener	0
/sitemap_post_6.xml.gz	No se ha podido obtener	0
/sitemap_post_7.xml.gz	No se ha podido obtener	0

Then I go to the Forum and ask for help and Arnaud told me to go here https://semperplugins.com/documentation/xml-sitemap-rewrite-rules-for-nginx/, but I don't know how to work with NGINX, and that wasn't my problem, my problem was:

No se ha podido leer el sitemap
Error general de HTTP
1 instancia

Se ha producido un error al intentar acceder al sitemap. Asegúrate de que cumpla nuestras directrices y de que se encuentre en la ubicación especificada y vuelve a enviarlo.
Ejemplos
**Error HTTP:
403**

Arnaud recommended me "If you don’t know anything about NGINX, then simply disabling Sitemap Compression should do the trick"

I did what he told me and I also put the map in 500 partitions, since the console says that it can´t read some sitemaps because they are very large, but with the same result not reading my sitemap.

Some time passed with no answer, so I decided to reduce to 250 partitions, and this worked for Google Search Console, but not with some post types (the most important for me):

https://www.dsdramas.com/sitemap_haru_film_1.xml
https://www.dsdramas.com/sitemap_haru_film_2.xml
https://www.dsdramas.com/sitemap_haru_film_3.xml
https://www.dsdramas.com/sitemap_haru_film_4.xml

And that's my problem right now. I asked my hosting service about the “Nginx” and they told me that I have “Nginx”, but as a proxy and “Apache” as a web server, so please if you can indicate me the rules I need for that environment. Preferably, indicate me the rules for the .htaccess because it would be the most standard method to use and I could manage it by editing the file directly.

Thank you,

Dalia

**Comment by wpsmort** [comment]
I tested again with two sites and both worked fine this time.  There's a chance that this was a transient with Google Search Console.  All of the sitemaps in the index for each site were processed much faster today than when I tested yesterday.

**Comment by michaeltorbert** [comment]
Update: it looks as though Google has made an undocumented change, and "_post_" in the sitemap name does not appear to be supported any longer.
