### ISSUE TITLE
indexing images or other media from private page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#261]
reported here:
https://wordpress.org/support/topic/do-private-posts-get-indexed-with-plugin?replies=4#post-8367030

Verify, then let's look at whether there's a good way to resolve this.

Some ideas:

a) checkbox on a media item's edit page to exclude it from the sitemap
b) global checkbox to exclude any media that is in a private page/post (the issue here is that it would exclude even if it's also on a public page/post, although we could maybe have it included in that case?)

Thoughts?

**Comment by diablodale** [comment]
If technically possible and performant, I would prefer that a post of type=media/attachment be excluded from the XML sitemap if all those posts dependent on it are private.

There may be some additional privacy concerns. For example, if a post of type=media/attachment is added/associated initially with a post, then its permalink may have the parent post's permalink within it. For example, post "/2016/05/01/foobarpost" has media "/2016/05/01/foobarpost/picfoo.png". Now consider the case that foobarpost is marked private. And...another post somewhere on the site chooses to reuse picfoo.png. I would expect the XML sitemap to include picfoo.png since at least one of its parent posts are not private. However, now the permalink of the private post is embedded in the link of the media; disclosing a tiny part of the private post.

I believe that scenario is a privacy concern rather than a code defect. A workaround could be to add the media directly using the media library and not via the post's 'add media'. In this way, the media will not have the initial parent posts's permalink in its own. Another workaround could be to use other permalink styles like plain or numeric. I don't think those styles embed the parent's permalink.

**Comment by arnaudbroes** [comment]
I was able to reproduce this. 

Use these steps:

1. Create a new Post, upload a new image and add it to the content section of the Post
2. Publish the Post as a private page
3. Go to Media and make sure that the image shows up as attached
4. Include Media in the sitemap via the XML Sitemap menu, view the sitemap and you'll notice the attachment for that image is included

**Comment by michaeltorbert** [comment]
The problem I see with this is that determining on which posts media is used isn't an exact science. In addition to the performance hit checking for something that's very much an edge case, there would be so many false positives resulting in unintentionally blocked images that are used elsewhere.
I think any solution would need to include explicitly blocking the private media, rather than AIOSEOP trying to determine it intelligently.

I'm going to go ahead and close this for now until such time exists that a better way forward is discovered.
