### ISSUE TITLE
repeated placeholder

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2638]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/admin/display/notices/review-plugin-notice.php#L24

The double placeholder is getting flagged. Do we know this works? 
https://translate.wordpress.org/projects/wp-plugins/all-in-one-seo-pack/dev/en-ca/default/?filters%5Bwarnings%5D=yes&filters%5Bstatus%5D=current_or_waiting&sort%5Bby%5D=translation_date_added

**Comment by michaeltorbert** [comment]
Another:
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/3da681fc9e66a522414b5c17398af93aca10ca3c/admin/class-aioseop-helper.php#L959

**Comment by arnaudbroes** [comment]
It works (see Dutch string below).
![image](https://user-images.githubusercontent.com/18156697/59590647-d31bb200-90ec-11e9-8f78-88f861b7d6b9.png)

We can change it to %1$s, %2$s but then we have to add the same argument twice. Using %s twice for a single argument is not an option because Grunt flags it. 

I'm good as it is but I'll change it to improve readability and make it less confusing.
