### ISSUE TITLE
Create release post for 3.2

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2716]
Create release post announcing what's new in the 3.2 release.

**Comment by arnaudbroes** [comment]
@wpsmort for your consideration - https://semperplugins.com/wp-admin/post.php?post=4996&action=edit&lang=en. 

I haven't written much on Schema.org since I won't be fully up to date on it till I get the chance to play around with some of the settings but I believe it's best that you write a dedicated post on Schema.org and that the release post links to it.

**Comment by wpsmort** [comment]
@arnaudbroes This post needs a Featured Image and an Open Graph image added.
