### ISSUE TITLE
Illegal string offset in schema/graphs/graph-organization.php

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2766]
Reported here - https://wordpress.org/support/topic/problem-after-updating-plugin-2/

Warning: Illegal string offset 'width' in /home/upwardsp/public_html/wp-content/plugins/all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 114

Warning: Illegal string offset 'height' in /home/upwardsp/public_html/wp-content/plugins/all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 115

**Comment by michaeltorbert** [comment]
The fix itself is pretty simple, but so far I've been unable to reproduce the warning. I tried setting $logo_meta to false in both PHP 5.3 and 7.3.

**Comment by wpsmort** [comment]
I have access to a cloned user site where I can reproduce this.  I have identified this as a conflict with the Composer theme from innwithemes.com.  It only happens when Use Schema.org Markup is Enabled and Person or Organization is set to Organization.

Here's the full set of warnings and notices generated:

Warning: Illegal string offset 'width' in all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 114
Notice: Uninitialized string offset: 0 in all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 114
Warning: Illegal string offset 'height' in all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 115
Notice: Uninitialized string offset: 0 in all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 115

**Comment by wpsmort** [comment]
@EkoJR I've got a cloned site for you to troubleshoot with.

**Comment by toxpal** [comment]
> I have identified this as a conflict with the Composer theme from innwithemes.com

You are talking about my cloned site then. However, be aware this issue might not be related to specific theme because the first user who reported this issue also included URL of his site. It's upwardspiralblog.com and it runs a different theme but still has the same problem.

**Comment by EkoJR** [comment]
@toxpal It is possible it isn't isolated to a single theme. Theme's that hook into customizer, and possibly uses its own settings as well, but the value returned isn't a numeric attachment ID. When it retrieves the meta data for the image when it is expecting an ID, it will return empty values. Which then creates the PHP illegal string offset error.

**Comment by vagelisp** [comment]
Hello all, we have the same issue on a website ( https://www.nectos.gr/ ) that doesn't use the theme you mentioned above.

**Comment by wpsmort** [comment]
@vagelisp As stated above, this is not isolated to a single theme.  It could affect any theme that hooks into the WordPress Customizer.  We already have a patch for this and will release it soon.  For the time being (and temporarily), you can fix this by setting Use Schema.org Markup to Disabled.
