### ISSUE TITLE
Undefined index notices with schema settings

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2772]
In certain circumstances, the following notices show on the frontend of a site and the Use Schema.org Markup option doesn't have anything selected:

Undefined index: aiosp_schema_site_represents in all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 59
Undefined index: aiosp_schema_organization_name in all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 75
Undefined index: aiosp_schema_site_represents in all-in-one-seo-pack/inc/schema/graphs/graph-website.php on line 59
Undefined index: aiosp_schema_search_results_page in all-in-one-seo-pack/inc/schema/graphs/graph-website.php on line 63
Undefined index: aiosp_schema_site_represents in all-in-one-seo-pack/inc/schema/graphs/graph-webpage.php on line 142

@EkoJR We discussed this and I believe it had to do with the version number in the database. However, we should look at fixing this.

**Comment by arnaudbroes** [comment]
If this is happening because of the version_compare() function, then you might want to add a conditional check to see whether the new keys in the schema markup setting array already exist (and which then runs the update_schema_markup() function if this is not the case). If we re-run it for everyone, I'm guessing we'll be overriding user's settings if they've already modified them.

**Comment by wpsmort** [comment]
Steps to reproduce:

1. Install AIO v3.1.1 on a new site
2. Enable Social Meta module
3. Go to AIO General Settings and click Update Options
4. Deactivate AIO
5. Download and unzip AIO v3.2.1
6. Change the version number to 3.1.1
7. ZIP up the files, upload to your site and active
8. View the homepage of your site and you should see the undefined index notices
9. Go to Schema Settings and you should see Use Schema.org Markup is neither Enabled to Disabled

This is happening when the version numbers are the same so the plugin doesn't think it's updated and because the the options under Schema Settings changed between 3.1.1 and 3.2 it generates the notices.

**Comment by EkoJR** [comment]
The problem occurs because changing the version number is what is preventing the database. That would be a flawed concept in WP, and the likelihood of that occurring is very little to none.

In the past, this was preventing a successful test because switching back and forth on versions during testing, the `old_version` isn't downgraded when downgrading the plugin. It remains at the latest version that was used on the website, and required the database options to be deleted.
