### ISSUE TITLE
Nextgen galleries not loading in 3.2

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2774]
reported here: https://wordpress.org/support/topic/new-version-3-2-x-conflict-with-nextgen/

**Comment by wpsmort** [comment]
@EkoJR I have been able to reproduce this on a clone of the users site.  

The conflict is between AIOSEOP and NextGen Plus.  It specifically happens when Use Schema.org is Enabled and the NextGen gallery is embedded using either Pro Slideshow or Pro Horizontal Filmstrip.  

Here's the steps to reproduce:

1. Install NextGen Gallery, NextGen Gallery Plus (paid plugin) and AIOSEOP v3.2x
2. Create a gallery and add some images
3. Create a post and add the gallery and select either Pro Slideshow or Pro Horizontal Filmstrip
4.  View the post and the gallery should display fine
5. Go to AIO settings and enable Use Schema Markup
6. View the post and the gallery should no longer appear.

I noticed that when this happens, the NetxGen Gallery Plus scripts get loaded in the header instead of the footer.  Not sure why this would be or if this is the cause.
