### ISSUE TITLE
Getting lots of characters on top of my blog posts after latest update

### ISSUE THREAD

**Issue by leandroprz** [semperfiwebdesign/all-in-one-seo-pack#2776]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**
https://leandroperez.com.ar/blog/como-agregar-multiples-subtitulos-a-un-dcp-con-cutedcptools/

**Describe the bug**
After updating to the latest version I started seeing lots of characters on top of every blog post: https://i.imgur.com/RqRB7dQ.png

**To Reproduce**
1. Go to this page: https://leandroperez.com.ar/blog/como-agregar-multiples-subtitulos-a-un-dcp-con-cutedcptools/
2. Check the top of the page.
3. See error

**Expected behavior**
Didn't expect to see any of these: https://i.imgur.com/RqRB7dQ.png

**Screenshots**
https://i.imgur.com/RqRB7dQ.png

**Version Info (please complete the following information):**
 - WordPress version: 5.2.2
 - All in One SEO Pack version: 3.2.1
 - PHP version: 7.0.29

**Comment by wpsmort** [comment]
@leandroprz The problem is that something in your theme or another plugin is injecting the following code into Schema.og JSON-LD code that All in One SEO Pack outputs:

<div style=\"margin: 8px auto 8px 0; width:70%;\"><script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"></script>\n        \n <ins class=\"adsbygoogle\"\n             style=\"display:block\"\n             data-ad-client=\"ca-pub-8944811441086902\"\n             data-ad-slot=\"7114069196\"\n             data-ad-format=\"auto\"\n             data-full-width-responsive=\"true\"></ins>\n <script>\n        (adsbygoogle = window.adsbygoogle || []).push({});\n</script></div>

Have you tested by clearing all caching, deactivating all plugins except All in One SEO Pack and switching to the default Twenty Nineteen theme?

If you recognize the code above then you should be able to tell what's injecting that into the output from All in One SEO Pack.

**Comment by leandroprz** [comment]
Seems to be a custom plugin I'm using that inserts Google Ads. The strange thing is this wasn't showing before the latest AIO update.

**Comment by wpsmort** [comment]
We just added a new feature that outputs Schema.org structured data markup on all posts, pages, etc.  It's this that your custom plugin is hijacking.  It's inserting its ad code whenever we output the post title.

**Comment by leandroprz** [comment]
Thanks. I just fixed my code.
