### ISSUE TITLE
Social Meta - OG tags in wrong order for Pinterest Rich Pins

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2804]
Reported here: https://wordpress.org/support/topic/rich-pins-meta-description-not-showing-up/#post-11817129

>I’ve been in touch with Pinterest support, and according to them the tags are in the wrong order.
>Here’s the message I received:
> _Hi Max,
> 
> I see that you have an issue with setting up a rich pin. I have checked the pin https://www.pinterest.co.uk/pin/660481101585482894/ you are referring to and in the webpage https://www.upwardspiralblog.com/natural-remedies-for-depression/ I see the tags you have placed are not in the right order format. I have attached screenshots for your reference and please make sure you follow the same order as mentioned in the format.
> 
> Please write back to us if you are still facing an issue so that I can check further and assist you accordingly.
> 
> Regards
> 
> Zach_
> 
> It seems that AIO has put the tags in the wrong order.

Resource: https://developers.pinterest.com/docs/rich-pins/articles/?

**Comment by maxw68** [comment]
Sorry, I should have included the screenshots Pinterest sent me.

![image](https://user-images.githubusercontent.com/53946871/62790900-f434c980-bac3-11e9-8fae-27c830e011ff.png)

![image](https://user-images.githubusercontent.com/53946871/62790905-fac34100-bac3-11e9-96f4-2cd73220ce21.png)

**Comment by michaeltorbert** [comment]
@maxw68 Ok that definitely helps. :)

**Comment by wpsmort** [comment]
I tested this by creating rich pins with the tags in the current order and in the "correct" order as per Pinterest's documentation.  Both worked fine when I validated the rich pins and when I posted them on Pinterest.  Changing the order of the tags didn't affect sharing on Facebook or Twitter.

I also checked some major sites such as BBC News, Time.com and Vogue and the OG tags are not in the correct order on those sites so I don't believe that the order of the tags matters otherwise those sites would have problems.

As it's trivial to change the order of the tags, I'll submit a PR for this.
