### ISSUE TITLE
Notice: Undefined index: aiosp_schema_site_represents in inc/schema/graphs/graph-organization.php on line 59

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2854]
Reported via email by Ola

**Comment by EkoJR** [comment]
Looks like the problem is with the updater class, and I believe we all tested for that and we were all unable to reproduce it; plus it was from a test when the database was not clean. The problem is the updater not running on the frontend when an update has occurred without accessing the admin side; either by updating by FTP or possible WP CLI.

## Steps to Reproduce

1. Git checkout to version 3.1.1.
2. Go to phpMyAdmin, select the site's database, in wp_options, delete aioseop_options.
3. Go to WP Admin in order to initialize AIOSEOP's database options.
4. Go to front end, and close all tabs displaying the WP Admin. (This prevents the WP Heartbeat on the admin side.)
5. Git checkout to version 3.2.4.
6. Refresh tab with front end displayed.

Error should then be displayed.

Navigating to the Admin side will also the error to go away. If the error is persistent, saving AIOSEOP's options will also make the error go away.
