### ISSUE TITLE
Preview Pictures not showing up when posting to Twitter

### ISSUE THREAD

**Issue by bostmaguy** [semperfiwebdesign/all-in-one-seo-pack#2904]
Whenever someone tweets a post from my Wordpress site, the preview image doesn't show up. I checked the source code, and it shows the Twitter meta information for the preview image is correct as supplied by All In One SEO:

<meta name="twitter:image" content="https://example.com/wp-content/uploads/2017/12/example.jpg" />

But the picture doesn't show up, making for an ugly tweet. It's gotten so bad I've gotten emails from people visiting my site. Also, it used to work, but started happening after one of the many upgrades to AIO SEO. Any help or ideas would be appreciated. 

I'm also using Jetpack (who isn't?) which adds the share buttons at the bottom of each post and also automatically posts the article to Twitter when I publish an article for the first time. Those tweets correctly show an image. It's only when a visitor tweets does the preview image not show up.
I also checked for duplicate meta tags and there were none. Only the ones supplied by AIO SEO. Thanks.

**Comment by michaeltorbert** [comment]
@bostmaguy 

Since you didn't share a URL, we couldn't tell you what's happening for certain. 
However, if AIOSEOP is correctly generating the meta information in the source code, that means AIOSEOP is correctly doing its job and the problem is elsewhere.
You can use the Twitter card validator tool to see what Twitter does with the info: https://cards-dev.twitter.com/validator
