### ISSUE TITLE
Bug - Conflict with WooCommerce Square plugin

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#3047]
Reported here: https://wordpress.org/support/topic/payment-error-ocurred-2

**Comment by arnaudbroes** [comment]
> I'm going to hold off spending more time on this issue till the user gets back to us since there won't be an easy to reproduce transactions and also because the plugin itself seems to have an absolutely terrible track record with lots of failed purchases

**Comment by wpsmort** [comment]
I've requested login info from the user.

**Comment by arnaudbroes** [comment]
Another WooCommerce Square issue has been reported here - https://wordpress.org/support/topic/credit-card-checkout-wont-allow-entry/#post-12219280. Not sure if it is related.

**Comment by wpsmort** [comment]
I was able to reproduce this and can confirm that this problem has been present since v2.2.2.  The problem only occurs when Run Shortcodes In Autogenerated Descriptions is enabled under General Settings or in the Social Meta module.

Steps to reproduce:
1. Install and configure the WooCommerce and add a product
2. Install and configure the WooCommerce Square plugin
3. Install AIOSEOP 
4. Test a purchase and it should work
5. Go to All in One SEO > General Settings > Advanced Settings and enable the Run Shortcodes In Autogenerated Descriptions option
6. Test a purchase and it should fail.  When checking out, nothing happens after completing the checkout form and clicking the Place Order button.

**Comment by arnaudbroes** [comment]
This should be as simple as adding their shortcode(s) to our conflicting shortcode array.

**Comment by arnaudbroes** [comment]
Bumping this to 3.3.5 since this has been reported again here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3047 - and it only takes a few minutes to fix this.

**Comment by adnankhan250** [comment]
DesiRulez is a desi forum for entertainment. A complete forum to 
share videos, listen to music, download cricket videos and ...


<a href="https://desirulez.su/desitvbox/">DesiTvBox</a>
