### ISSUE TITLE
Bug - Preview Snippet hangs for long posts

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#3050]
Not really a bug but for long posts the Preview Snippet may hang while it the JavaScript code processes the content to figure out the description.

By reducing the amount of characters it has to process, we should be able to reduce the impact.

**Comment by arnaudbroes** [comment]
@EkoJR can you see if you can reproduce this?

**Comment by EkoJR** [comment]
The problem is with the Regex 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/9cd79a41978c6f7d28ec5a46bdf4d6957721adaf/js/admin/aioseop-preview-snippet.js#L142

![snippet_performance](https://user-images.githubusercontent.com/2794445/69275610-94a18c00-0b91-11ea-9b29-9de6f746755d.PNG)

## Steps to Reproduce

1. Just have AIOSEOP active; Classic Editor plugin is not required.
2. Create a new post.
3. In the content, using Gutenberg, click the + button to select the block type, and select Classic.
4. Add 10000+ characters to the post.
5. Typing additional characters in content begins to cause the UI to hang.
