### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in

### ISSUE THREAD

**Issue by keyansuo** [semperfiwebdesign/all-in-one-seo-pack#3066]
**Describe the bug**
Warning: Invalid argument supplied for foreach() in /www/wwwroot/XXXXXXXX/wp-content/plugins/all-in-one-seo-pack/inc/translations.php on line 167

Warning: Invalid argument supplied for foreach() in /www/wwwroot/XXXXXXXX/wp-content/plugins/all-in-one-seo-pack/inc/translations.php on line 215

**To Reproduce**

**Screenshots**
![20191128232220](https://user-images.githubusercontent.com/58302817/69817629-fc14a700-1235-11ea-8e0f-d579de9efcdb.png)

**Version Info (please complete the following information):**
 - WordPress version:5.3.0
 - All in One SEO Pack version:3.3.3
 - PHP version:7.3.12

**Comment by arnaudbroes** [comment]
@keyansuo thank you for reporting this. I'm afraid that I'm unable to reproduce this. 

I had a quick look at our code and it looks like we simply fetch some meta data about locales from a remote endpoint from WordPress.org. If you're seeing that error, then that's likely because our plugin didn't receive a 200 OK response from the remote endpoint (which could happen for a number of reasons).

If you're still experiencing this issue, then you might want to check your firewall configuration (if you're using one).
