### ISSUE TITLE
Version 3.3.3 still doesn't work with Ark theme

### ISSUE THREAD

**Issue by andrewst123** [semperfiwebdesign/all-in-one-seo-pack#3072]
Your latest version (3.3.3) still doesn't work with the Ark theme.

**Comment by wpsmort** [comment]
@andrewst123 You have not provided any detail here so it's hard for us to help you.  

If you wish to report a possible bug then first make sure you've followed the steps in this article - https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

Once you've confirmed that it's not caused by another plugin or that it's not a bug with the theme then you can open a bug report here: 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new?assignees=&labels=&template=bug_report.md

You must complete the bug report form completely and be prepared to provide us with a copy of your theme and possible access to your site if we're unable to reproduce the problem.

**Comment by arnaudbroes** [comment]
Duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3061 btw.
