### ISSUE TITLE
Capitalize Category Titles no longer works in the current release

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#320]
The option under Title Settings for Capitalize Category Titles no longer works.  

Category titles are always lowercase now.

There was a change in version 2.3.3 where category titles were always being capitalized to category titles always being lowercase.

**Comment by michaeltorbert** [comment]
@wpsmort Can you verify that it broke in 2.3.3? We had some problem (pre-github) where I think our capitalize category titles code was messing up something... either a) had to do with woocommerce or b) the code was running too many times and messing up. 
The code is back now (I'd uncommented it for some reason) and it seems to be working. The problem is I'm not sure why I uncommented it to begin with, so we need to know when it was to try and figure out why and so I'm not sure if something else may be broken now...

**Comment by wpsmort** [comment]
@michaeltorbert: I have confirmed this stopped working in v2.3.3.  I have tested and it is working now.
