### ISSUE TITLE
Version 4.3.3 broke query loop to cpt, pages, post after updating to WordPress 6.2

### ISSUE THREAD

**Issue by whimsyniche** [semperfiwebdesign/all-in-one-seo-pack#3208]
Check out the debug at 

https://wordpress.org/support/topic/all-in-one-seo-plugin-not-allowing-new-posts-on-blog-since-wordpress-6-2-update/

**Comment by wpsmort** [comment]
Hi @whimsyniche,

I'm sorry for the issue you experienced with All in One SEO today.

We've just released version 4.3.4.1 which fixes this issue.

The issue was caused by a conflict between our plugin and the emoji script of WordPress due to changes to that script in WordPress v6.2.

Please update to this latest version of All in One SEO and make sure to clear all caching, including server-side caching, WordPress caching (through any caching plugins), and browser caching.

Let us know if you still experience any issues after doing this.

**Comment by whimsyniche** [comment]
@wpsmort Thanks for the update!

**Comment by whimsyniche** [comment]
Welcome to close this issue.
