### ISSUE TITLE
Make user profile meta fields obvious

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#39]
It should be obvious that these fields are for AIOSEOP and not built into WP or from another plugin. related to #40

**Comment by wpsmort** [comment]
Here's a screenshot of how this should potentially look:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14157709/4d92cd3e-f69a-11e5-986f-d8b76ddafbbd.png)

**Comment by iko-dev** [comment]
The image given in description is repeating the "Social Media Info" i.e. Google+, Twitter and Facebook. Attached is our understanding, please confirm or explain if we understood otherwise.

![user profile - issue 39](https://cloud.githubusercontent.com/assets/18193659/14583598/5eaae954-0440-11e6-8afd-92b823592f16.png)

**Comment by wpsmort** [comment]
Your understanding is correct and your mockup matches what we want.

**Comment by iko-dev** [comment]
thanks for reply, we will let you know after reviewing it.

Question: should we confirm each step with you before applying? or can we use our judgement to save time. And then explain you the reason.

**Comment by wpsmort** [comment]
You can just go ahead and submit your code for review once you have finished.

**Comment by michaeltorbert** [comment]
@iko-dev There's nothing in the pull request. You have to commit your changes to your fork first.

**Comment by iko-dev** [comment]
Please check now.

Little Explanation about the task:
Its not possible to add title directly into this section. Because filters are used in this contact section and filters only provide fields and labels. So we added "All in one SEO" as field and hide out the input field in css.

The other option is to bring this "All in One SEO" section down in the end, in this way it disappears from users eye on first look.

**Comment by michaeltorbert** [comment]
@iko-dev Pull requests need to be into the iko-dev branch, not master.

**Comment by iko-dev** [comment]
Do you have access to this location
https://github.com/iko-dev/all-in-one-seo-pack/pull/1

**Comment by michaeltorbert** [comment]
Whoever takes this over can look at the various closed PRs for guidance.
