### ISSUE TITLE
Add @since to each function docblock

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#405]
Each function has a PHP Docblock. 
Most of these are missing the "since" tag.

**Comment by michaeltorbert** [comment]
Well that example didn't keep the formatting...

**Comment by arnaudbroes** [comment]
@michaeltorbert 
Finally finished up backlog and started with this.

So I started with the first version (0.6.2.6), a barebone version of what the plugin is now.
There's just one file all_in_one_seo_pack.php that doesn't look anything like the current version, which makes sense.

Just doublechecking if I can ignore that file and only start adding @since tags once I can actually find recurring functions in the newer versions? Ping me on SKYPE if this doesn't make sense and I'll give you a quick call.

**Comment by arnaudbroes** [comment]
@michaeltorbert finished adding @since tags to /admin/; if you could check those files before I continue, that would be great
