### ISSUE TITLE
improve accessibility

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#435]
Use tools like Chrome plugins:

"color contrast analyzer"
"wave"
"Accessibility Developer Tools"

**Comment by michaeltorbert** [comment]
Related to #2534

**Comment by wpsmort** [comment]
I've opened a PR that takes care of the low hanging fruit for making the UI more accessible.  

Here are the items that still need to be resolved along with my comments:

1. Feature Manager:  You can't tab between the modules which means that you can't activate or deactivate a module by using only the keyboard.  @arnaudbroes This may be something you can fix with JS.

2. There are color contrast problems with all buttons that use the built-in WP class "button-primary".  This is a known issue that needs to be fixed in WordPress (https://core.trac.wordpress.org/ticket/47151).

3. Form inputs must have labels.  This affects every form field in the plugin UI and is an architectural problem that needs significant changes to the way we output form fields so that labels and inputs are not contained in different divs.  This could be fixed by using the WordPress UI instead of our own custom UI.

4. Checkbox and radio inputs for the same option should be grouped by fieldset or ARIA group.  This is related to item 3 above.
