### ISSUE TITLE
Collapsing the mailing list field collapses all general settings

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#460]
Reported here: https://wordpress.org/support/topic/join-our-mailing-list-module/

We need to see what version this started.

**Comment by arnaudbroes** [comment]
Seems like this has never worked as it should. 

The mailing list section was introduced in version 2.1.0.0 and has caused issues since then:

![image](https://cloud.githubusercontent.com/assets/18156697/18626202/c7aa80a8-7e53-11e6-83d6-b47f4ca86197.png)

**Comment by arnaudbroes** [comment]
@michaeltorbert 
It's a positioning bug. 
The sections do not disappear, but are pushed underneath the About & Advertisement section when the Hide Button is toggled.

It also bugs on the other pages where the Join Mailing List section is present.
(e.g. Performance)

Seems like this feature has caused positioning issues since its release:
(first version 2.0.1.0)

![image](https://cloud.githubusercontent.com/assets/18156697/18626531/ed8f120a-7e55-11e6-854d-7ded410d7365.png)

Current version 2.3.9.2:

![image](https://cloud.githubusercontent.com/assets/18156697/18626601/4e2bcb12-7e56-11e6-9659-ef6de3e2668c.png)

The About and Advertisement Section move to the left when the Newsletter section is minimized while pushing the other settings underneath them.

The same applies to the General Settings page:

![image](https://cloud.githubusercontent.com/assets/18156697/18626666/ba02d600-7e56-11e6-80cb-961e43cc2d0f.png)

Just ping me if this isn't clear.

**Comment by wpsmort** [comment]
This is fixed and tested
