### ISSUE TITLE
Description count is off and description sometimes changes when clicking in the field

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#516]
Reported by R Tinkler via email:

_Please try editing  a current post. For example: ---------

You’ll notice that the ‘Beschreibung’ (Description) field is indicating 159 Characters. If you copy the text into a Word file, you will notice that there are actually only 150 characters. When I click into the ‘Beschreibung’ Field, the number suddenly changes from 159 to 151._

That site is using AIOSEOP Pro, Advanced Custom Fields: qTranslate, All in One SEO Pack & qTranslate-X, qTranslate-X

This is verified on the user's site.

**Comment by wpsmort** [comment]
This issue is caused by the way the qTranslate-X and All in One SEO Pack & qTranslate-X plugins work.  qTranslate-X adds shortcodes around the meta description for the language, for example:

[:de]This is my German description[:]

In older versions of qTranslate-X the shortcodes would remain in our fields, but in the version running on this site they get hidden, but because they are only hidden, All in One SEO Pack still counts the characters.  

In the latest version of qTranslate-X they convert the shortcodes to a language name like so:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/19090552/04c0c47a-8a4d-11e6-8410-9788788281b2.png)

This messes up our character counter because we still see the language name and count it.  

This is a compatibility issue with qTranslate-X and possible other forks of the qTranslate plugin.

**Comment by wpsmort** [comment]
Reported again by Roberto Lizano on 1/8/17 by email.

**Comment by wpsmort** [comment]
I have found that this bug no longer occurs with the latest version of qTranslate-X v3.4.6.8.
