### ISSUE TITLE
XML Sitemaps module - Remove Filename Prefix field

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#520]
We should remove this field but make sure we support users who have entered something different from the default name (sitemap).

<img width="791" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/18966031/b1aaab46-864d-11e6-8622-b773ebd0fbd2.png">

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1449

Should something similar be supported for the video sitemap module as well?

**Comment by frankf2** [comment]
For those of us who manage private websites, e.g., HS Class, in addition to public sites, retaining the ability to specify a custom sitemap name is helpful.  It allows us to use a caching program (W3 Total Cache - fixed) that reads the sitemap to prime the page cache, while not exposing (due to custom sitemap name) a list of pages, images, and associated page name content to outsiders, including malicious parties, due to the well-known sitemap name.

**Comment by michaeltorbert** [comment]
Hi Frank,

Thank you for sharing your thoughts. This is certainly open for discussion, as we want to develop the plugin with the best interest of users in mind.

The reason we did this was to make the UI more less complex/confusing, and this is something that very few people would use, and in most cases isn't at all necessary.

Also, we were already planning on introducing a new API filter hook to let site owners change the sitemap name, in lieu of the option.
For those with sitemap names already changed prior to version 2.6, this will be respected, rather than reverting back to sitemap.xml

**Comment by frankf2** [comment]
Thanks for considering.
