### ISSUE TITLE
Snippet preview and post seo desc default don't filter out html

### ISSUE THREAD

**Issue by dawatorbert** [semperfiwebdesign/all-in-one-seo-pack#672]
![screen shot 2016-12-06 at 7 32 09 pm](https://cloud.githubusercontent.com/assets/18234064/20950005/d5aa803e-bbea-11e6-9f9a-1e33b937eb02.png)

**Comment by wpsmort** [comment]
This only affects WooCommerce product short descriptions.  It's because the Product Short Description was developed as the Post Excerpt field for Products and you can't use HTML in the Post Excerpt.  But now that they've added the TinyMCE editor to the Product Short Description you can use it like the Post Content field and put HTML and shortcodes in the Product Short Description.  

We therefore need to add code to parse any HTML added to the Product Short Description when using auto-generated meta descriptions before displaying the preview snippet.

**Comment by wpsmort** [comment]
I tested this in pull request 835 and it was fixed.  I opened a new issue #837 for the same problem on the Social Settings tab.

**Comment by stanislavsa** [comment]
I added fix for an issue #837 in the pull request 835. Also placed the code that filters out tags for snippet preview before the code that truncates snippet preview description so for now snippet preview and post seo description placeholder displays text with the same length.

**Comment by wpsmort** [comment]
@stanislavsa I tested this further with more HTML tags but using different format buttons from the TinyMCE bar in the Product Short Description field.  I found that certain text formatting seems to break this.  I believe it's because the HTML markup is being included in the number of characters and once we reach 160 characters we don't display anything more in the Description field.  For example:

This is getting counted as 160 characters:
<span style="color: #ff0000;">Lorem</span> <span style="text-decoration: underline;">ipsum</span> dolor sit amet

But in fact, once you strip out the HTML there's only 27 characters of text there.

**Comment by stanislavsa** [comment]
@wpsmort ok, I'l check one more time

**Comment by stanislavsa** [comment]
@wpsmort yes, you was right. The number of symbols was incorrect. I figured out where the description truncates in the code and did some changes.

**Comment by wpsmort** [comment]
@stanislavsa This works now, thanks.  Can you submit a new pull request and I'll mark it for testing.

**Comment by wpsmort** [comment]
This is tested and is good.  Needs final code review.
