### ISSUE TITLE
Uncaught exception ‘BadMethodCallException’ generate_htaccess_blocklist

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#734]
Reported here - https://wordpress.org/support/topic/uncaught-exception-badmethodcallexception-generate_htaccess_blocklist/

User states that when updating to WordPress v4.7.2 they get a white screen and this error in the debug log:

Method generate_htaccess_blocklist doesn’t exist’ in /path/to/wordpress/wp-content/plugins/all-in-one-seo-pack/admin/aioseop_module_class.php:52

User is running nginx.

**Comment by wpsmort** [comment]
Reported again here - https://semperplugins.com/support/install-upgrade-all-in-one-seo-pack-pro/issue-with-upgrade-to-2-4-11-1/#p6207

I had to install v2.4.11 of Pro in order to get this 500 error to go away.  Here is the error:

[30-Jan-2017 23:05:55 UTC] PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Method generate_htaccess_blocklist doesn't exist' in /wp-content/plugins/all-in-one-seo-pack-pro/admin/aioseop_module_class.php:52

This user is running Apache.

**Comment by michaeltorbert** [comment]
The problem is that generate_htaccess_blocklist() is called when updating from older versions of AIOSEOP by our update scripts to remove certain words from being blocked (DOC, etc). 
In #657 we removed htaccess functionality, including this function, but it's still called when someone updates from one of those earlier versions.
I'ver removed the function call in the update script so this should fix it. Hopefully we don't break our update code that removes the words from the HTTP blocklist. :)

**Comment by michaeltorbert** [comment]
For testing:

1) Verify the fix by first verifying the method of reproducing the bug. Updating from <2.3.8 to master should do it. Once we've verified how to reliably reproduce the bug, verify that it's fixed in dev.

2) We also may want to retest #218, #34, etc where we removed things like DOC and Yandex from the Bad Bots list and make sure we didn't break that.

**Comment by wpsmort** [comment]
I tested going from v2.3.7 to master and was able to reproduce the error.  I then tested going from v2.3.7 to dev and confirm that there is no error.  

I also tested going from v2.3.4 to dev and Yandex was not removed from the .htaccess file but was removed from the list in Bad Bot Blocker.  This is because we've removed the code to do with writing to the .htaccess file.

We agreed that this one is resolved.
