### ISSUE TITLE
XML Sitemap - Add the URL from our XML Sitemap to our robots.txt file

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#86]
The screenshot below shows the default robots.txt file we use in our Robots.txt module.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14157113/a12b17ec-f697-11e5-98a5-1b11efde234b.png)

If the user is using our XML Sitemap module to generate their XML Sitemap then we should add the URL for the XML Sitemap to the robots.txt file where it says:

Sitemap:

**Comment by michaeltorbert** [comment]
Ok now when you "optimize" your robots.txt it should add the URL for the sitemap. This won't do anything for people who already have sitemaps (unless they optimize it again). Instead of spending the time dealing with that, my suggestion is we just wait until we create dynamic robots.txt, if we end up doing that.

**Comment by wpsmort** [comment]
This is tested and is fine.
