### ISSUE TITLE
Cannot uncheck Capitalize Tag and Search Titles

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#894]
I noticed today that you cannot uncheck the Capitalize Tag and Search Titles checkbox under General Settings > Title Settings.

When you mouse over the checkbox the cursor does not change and if you inspect the div then you see what appears to be the wrong class and ID:

class="aioseop_wrapper aioseop_no_label  aioseop_hidden_type"
id="aiosp_force_rewrites_wrapper"

**Comment by wpsmort** [comment]
I tested back and found this originated way back in version 2.0.2.

**Comment by wpsmort** [comment]
We found a hidden field that overlaps the Capitalize Tag and Search Titles field which prevents you from being able to click the checkbox.  The hidden field is the one with the ID aiosp_force_rewrites_wrapper and is on line 401 of the main class file.  It has a height of 0px which is what makes it hidden, changing the height fixes the issue of being able to click the checkbox.  

Deleting the code from line 401 of the main class file appears to fix the issue but we need to figure out why that code is there.

**Comment by michaeltorbert** [comment]
Pay special attention to code like:
`if ( ! empty( $aioseop_options['aiosp_rewrite_titles'] ) ) {
			$force_rewrites = 1;
			if ( isset( $aioseop_options['aiosp_force_rewrites'] ) ) {
				$force_rewrites = $aioseop_options['aiosp_force_rewrites'];
			}
			if ( $force_rewrites ) {
				ob_start( array( $this, 'output_callback_for_title' ) );
			} else {
				add_filter( 'wp_title', array( $this, 'wp_title' ), 20 );
			}
		}`

**Comment by michaeltorbert** [comment]
What looks like is happening is that the toggle itself for force writes (output buffering) is located in Performance, but we need to access the setting in the aioseop_class.php, so for some reason, instead of accessing the options array that should have it anyway, the Performance setting itself toggles the hidden option on the main options page.

**Comment by michaeltorbert** [comment]
Ok, so in the olden days, the force_rewrites was an options in the main settings page/class (which was the only place for settings in those pre-module days).
In order to move the setting to performance, but not perform a database migration, a prior developer simply made it a hidden field with the "solution" described above.

My advice is we do the database migration and remove it from the options in aioseop_class.php, then access it in that file from the performance module.

**Comment by wpsmort** [comment]
We have decided to just remove this option and all related functionality.  See issue #530
