### ISSUE TITLE
Make it easy to add to composer

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#939]
Shown here: http://bit.ly/2s1xaSU

**Comment by amostajo** [comment]
Why would you want to add the entire plugin to packagist? You should only include the `composer.json` file to handle dependencies.
Composer does not work as a repository, all packages downloaded in a project are stored in a vendor folder located at the root of the project, makes no sense to register the entire plugin as a package because (1) there will be no way to load files properly into wordpress, (2) it does not work as a repo, (3) does not autoload css/js files.

What should be done here is to make segmentation of the code. Like adding different packages for different purposes and loading them with composer, for example a package called `aioseo_core` amd this package will provided with all core classes like `aioseop_module.php` and maybe ``aioseop_class.php`. Then create you can create other packages per module, so can be maintained separately.
