### ISSUE TITLE
Remove schema for WooCommerce product pages

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#944]
This is reported and requested fairly often. 
WooCommerce adds its own product info, so ours conflicts. We give (pro) users some code using our API to remove it, but perhaps we should have it built into the plugin?

This may be something we just want in the WooCommerce upgraded functionality for Pro.

I know we have some other schema stuff we're working on, but this is something that could be easily and quickly implemented in the meantime.
Thoughts? Are there any times our schema code should not be removed on WC product pages?

**Comment by wpsmort** [comment]
I've tested this and confirmed that it is a problem.  We should build this into the plugin so that on products we remove our Schema markup.  I think this should be functionality in Pro.

We should consider what to do once we add the new JSON-LD markup.  If we product better markup that WooCommerce, do we want to offer Pro users the ability to use our markup instead of the markup in WooCommerce.

**Comment by michaeltorbert** [comment]
@wpsmort Does this still apply since we've removed schema? Will it apply with our new schema code?

**Comment by wpsmort** [comment]
This no longer applies as we are no longer outputting any Schema markup on product pages that conflicts with WooCommerce.  Issue #413 resolved this.
