### ISSUE TITLE
Pagination not applied to custom canonical URLs

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#948]
Reported here - https://wordpress.org/support/topic/wrong-canonical-url-at-certain-paginations-pages/

If you have Enable Custom Canonical URLs checked and set a custom canonical URL for a post with paginated content, the custom canonical URL appears without the page number on the end.

For example:

First page - link rel="canonical" href="http://aioseop.dev/my-custom-canonical-url/"
Second page - link rel="canonical" href="http://aioseop.dev/my-custom-canonical-url/"
Third page - link rel="canonical" href="http://aioseop.dev/my-custom-canonical-url/"

The correct URLs for second and third pages should be:

 Second page - link rel="canonical" href="http://aioseop.dev/my-custom-canonical-url/2/"
Third page - link rel="canonical" href="http://aioseop.dev/my-custom-canonical-url/3/"

**Comment by hadingrh** [comment]
Thanks to report here @wpsmort 

It's a serious issue for a web using custom canonicals. Because I experienced a drop rankings for some targeting articles, that other URL used canonical pointed those articles.

I update the issue here.
Seems that the plugin use a wrong canonical, if the the first position on a certain page having a custom canonical. It will not happened if the article that having a custom canonical is other that the first position (e.g at second, third, fourth, so on).
I'll give you a live example.
The https://www.richamorindonesia.com/masker/ is hava a custom canonical to https://www.richamorindonesia.com/cara-memutihkan-kulit-secara-alami-dan-aman/
At the page 19 (https://www.richamorindonesia.com/page/19/), where the article archieved (that is at the first position), the page is canonicalized to <link rel="canonical" href="https://www.richamorindonesia.com/cara-memutihkan-kulit-secara-alami-dan-aman/" />, not to <link rel="canonical" href="https://www.richamorindonesia.com/page/19/" />

I hope this info can make event clear of the issue.

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1473
