### ISSUE TITLE
Single apostrophe is changed to two in Doc title

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#961]
Reported here: https://wordpress.org/support/topic/july-update-adding-an-extra-to-my-title/ to have broken in 2.3.14

**Comment by wpsmort** [comment]
@michaeltorbert @amostajo I was able to reproduce this on a brand new site.  The problem is with the %blog_title% part of the title tag. To reproduce this follow these steps:

- Set up a site where the Site Title has an apostrophe, i.e Steve's Test Site
- Activate AIOSEOP v2.3.14 with default config
- Visit any page or post on the site and look at the browser tab, you should see the two apostrophes, see screenshot below

I tested this with all versions of PHP from 5.2 to 7.1 and got the same result.

<img width="577" alt="screen shot 2017-07-14 at 9 55 26 am" src="https://user-images.githubusercontent.com/17548525/28215059-a94cdea0-687a-11e7-8bf6-1be4049c5d3f.png">

**Comment by michaeltorbert** [comment]
In my testing I just left everything blank but put Michael's site in the site title in WordPress General Settings (not AIOSEOP settings) and it showed up as a quotation mark.

**Comment by michaeltorbert** [comment]
The problem is that &#039; (which is a single quote) is being checked for in aioseop_class.php:4913

**Comment by amostajo** [comment]
@michaeltorbert The change is partially fine. But we might need to include the charcode conversion in the preg_replace to support PHP5.2.

See this [commit](https://github.com/amostajo/all-in-one-seo-pack/commit/d0726995241c3e76d16b2fb452c3520621b38c3d) on my fork.
