### ISSUE TITLE
Issue when using post title as description

### ISSUE THREAD

**Issue by Toast707** [semperfiwebdesign/all-in-one-seo-pack#986]
Hi,

I'm currently trying to get AIO seo to use the post title as the description, but I'm having a bit of difficulty.

I've tried using both %post_title% and %wp_title% but neither are displaying. Is this a common issue?

Currently using php 7.1.7. WP version 4.8

**Comment by michaeltorbert** [comment]
From preliminary testing, it looks like there may be a bug that causes the meta description to only show up if something is entered in the SEO description field for the post, regardless of the description template settings.

**Comment by Toast707** [comment]
@michaeltorbert Hey, good to know it's not only me. Do you know what custom field the the descriptions are stored as?

**Comment by michaeltorbert** [comment]
@Toast707 The field is _aioseop_description but that's only for manually entered ones. Otherwise they're generated dynamically (on the fly) and not stored in the database.

**Comment by Toast707** [comment]
Yeah, I was just looking for a temporary work-around until it gets patched. Thanks for the heads up; looking forward to the update. I'll close the issue.

**Comment by michaeltorbert** [comment]
Reopening, as this is a legitimate bug.

**Comment by Toast707** [comment]
Sorry about that; I wasn't under the impression I was the first to post this issue.

**Comment by wpsmort** [comment]
@michaeltorbert I tested on a new install with the current live version of AIOSEOP.  There was no meta description until I activated the Autogenerate Descriptions option.   Once I activated that option, the meta description was generated from my post excerpt or the post content as expected.  

I then changed the Description Format to %post_title% and got the following meta description:

```<meta name="description"  content="Test post with excerpt | testsite" />```

The above is the post title and site title which is a potential issue because I didn't use %blog_title% in the Description Format field.  If I use %post_title% | %blog_title% in the Description Format field then I get the site title output twice. 

I also tested with %wp_title% and that worked perfectly fine. 

In fact I tested all the supported strings listed in the help for the Description Format field and they all worked fine with that one exception of the %post_title% including the site title.

The only other issue was that the placeholder text in the Description field in AIOSEOP did not show the correct description as per the format I selected, instead it always showed my post excerpt text.

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1421 solves part of the issue i.e. when you specify %post_title% in the description, now it will not add the blog title as the suffix.

Also seems related to #1408
