### ISSUE TITLE
Conflict with WebDorado Slider plugin

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#989]
Reported by email from Rodney Thompson.

When AIOSEOP is active on a site with the WebDorado Slider plugin, sliders don't load.

**Comment by michaeltorbert** [comment]
This is caused by that plugin's improper use of wp_print_scripts() instead of wp_enqueue_scripts(). Disabling the "Include scripts/styles only on necessary pages" option in the plugin will resolve the issue for users, but my suggestion is for anyone affect to simply use a better written slider plugin.

**Comment by michaeltorbert** [comment]
In this case, the extra bad calls to javascript (generated by the shortcode) were being pulled in by our OG description field. We "fixed it" for this particular user by simply disabling running shortcodes in OG descriptions.
